force-app/main/default/objects/QB_Auth__c/QB_Auth__c.object-meta.xml
<CustomObject>
    <label>QB Record</label>
    <nameField>
        <label>System Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>QB Records</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/QB_Auth__c/fields/Access_Token__c.field-meta.xml
<CustomField>
    <fullName>Access_Token__c</fullName>
    <label>Access Token</label>
    <length>1000</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/QB_Auth__c/fields/Access_Token_Expires_In__c.field-meta.xml
<CustomField>
    <fullName>Access_Token_Expires_In__c</fullName>
    <label>Access Token Expires In</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/QB_Auth__c/fields/App_Token__c.field-meta.xml
<CustomField>
    <fullName>App_Token__c</fullName>
    <label>App Token</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/QB_Auth__c/fields/OAuth_Key__c.field-meta.xml
<CustomField>
    <fullName>OAuth_Key__c</fullName>
    <label>OAuth Key</label>
    <type>TextArea</type>
</CustomField>

force-app/main/default/objects/QB_Auth__c/fields/oAuth_Secret__c.field-meta.xml
<CustomField>
    <fullName>oAuth_Secret__c</fullName>
    <label>oAuth Secret</label>
    <length>256</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/QB_Auth__c/fields/Production__c.field-meta.xml
<CustomField>
    <fullName>Production__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Production?</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/QB_Auth__c/fields/Realm_ID__c.field-meta.xml
<CustomField>
    <fullName>Realm_ID__c</fullName>
    <label>Realm ID</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/QB_Auth__c/fields/Redirect_Uri__c.field-meta.xml
<CustomField>
    <fullName>Redirect_Uri__c</fullName>
    <label>Redirect Uri</label>
    <type>Url</type>
</CustomField>

force-app/main/default/objects/QB_Auth__c/fields/Refresh_Token__c.field-meta.xml
<CustomField>
    <fullName>Refresh_Token__c</fullName>
    <label>Refresh Token</label>
    <length>1000</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/QB_Auth__c/fields/Refresh_Token_Expires_In__c.field-meta.xml
<CustomField>
    <fullName>Refresh_Token_Expires_In__c</fullName>
    <label>Refresh Token Expires In</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/QB_Auth__c/fields/Token_Time__c.field-meta.xml
<CustomField>
    <fullName>Token_Time__c</fullName>
    <label>Token Time</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/classes/QBRedirectController.cls
public class QBRedirectController 
{
    private QBOAuth qbAuth = null;    
    public QBOAuth.AuthResponse response {get;set;}    
    public String qbAuthName {get;set;}
    public Boolean isProduction  {get;set;}
    
    public QB_Auth__c queryExistingQBAuth() 
    {
       return [SELECT Name, App_Token__c, OAuth_Key__c, OAuth_Secret__c, Redirect_Uri__c, 
                     Production__c FROM QB_Auth__c 
               WHERE  Active__c = true 
               ORDER BY CreatedDate DESC 
               Limit 1];
    }
    public QBRedirectController() 
    {
        QB_Auth__c qbDbAuth = queryExistingQBAuth();
        this.qbAuthName = qbDbAuth.Name;
        this.isProduction = qbDbAuth.Production__c;
        this.qbAuth =  new QBOAuth(qbDbAuth.OAuth_Key__c, qbDbAuth.OAuth_Secret__c, null, qbDbAuth.Redirect_Uri__c);
        this.qbAuth.state = String.valueOf(Crypto.getRandomLong());
    }

    public String getLoginUrl() 
    {
        return this.qbAuth.getLoginUrl();   
    }

    public PageReference parseCode() 
    {
        String code = ApexPages.currentPage().getParameters().get('code');
        String companyId = ApexPages.currentPage().getParameters().get('realmId');
        String state = ApexPages.currentPage().getParameters().get('state');
        if (!String.isBlank(code)) 
        {
            response = this.qbAuth.authenticate(code);
            QB_Auth__c auth = queryExistingQBAuth();
            auth.Refresh_Token__c = response.refresh_token;
            auth.Access_Token__c = response.access_token;
            auth.Realm_ID__c = companyId;
            auth.Token_Time__c = System.now();
            auth.Refresh_Token_Expires_In__c = response.getRefreshTokenExpiry();
            auth.Access_Token_Expires_In__c = response.getAccessTokenExpiry();
            update auth;
        }
        
        return null;
    }
}