force-app/main/default/objects/Torc_API_Call__c/Torc_API_Call__c.object-meta.xml
<CustomObject>
    <label>Torc API Call</label>
    <nameField>
        <displayFormat>CALL-{000000000}</displayFormat>
        <label>Sequence</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Torc API Calls</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Torc_API_Call__c/fields/Contact__c.field-meta.xml
<CustomField>
    <fullName>Contact__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Contact</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Torc API Calls</relationshipLabel>
    <relationshipName>Torc_API_Calls</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Torc_API_Call__c/fields/Operation__c.field-meta.xml
<CustomField>
    <fullName>Operation__c</fullName>
    <label>Operation</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>INSERT</fullName>
            </value>
            <value>
                <fullName>UPDATE</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Torc_API_Call__c/fields/Torc_Id__c.field-meta.xml
<CustomField>
    <fullName>Torc_Id__c</fullName>
    <label>Torc Id</label>
    <length>80</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Torc_API_Call__c/fields/Torc_Match__c.field-meta.xml
<CustomField>
    <fullName>Torc_Match__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Torc Match</label>
    <referenceTo>Torc_Match__c</referenceTo>
    <relationshipLabel>Torc API Calls</relationshipLabel>
    <relationshipName>Torc_API_Calls</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Torc_API_Call__c/fields/Type__c.field-meta.xml
<CustomField>
    <fullName>Type__c</fullName>
    <label>Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Job</fullName>
            </value>
            <value>
                <fullName>User</fullName>
            </value>
            <value>
                <fullName>Match</fullName>
            </value>
            <value>
                <fullName>Torc_Match</fullName>
            </value>
            <value>
                <fullName>Resume</fullName>
            </value>
            <value>
                <fullName>Note</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Torc_Job_Opportunity__c/Torc_Job_Opportunity__c.object-meta.xml
<CustomObject>
    <label>Torc Job Opportunity</label>
    <nameField>
        <label>Torc Job Opportunity Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Torc Job Opportunities</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Torc_Job_Opportunity__c/fields/External_id__c.field-meta.xml
<CustomField>
    <fullName>External_id__c</fullName>
    <externalId>true</externalId>
    <label>External Id</label>
    <length>50</length>
    <required>true</required>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/Torc_Job_Opportunity__c/fields/externalJobId__c.field-meta.xml
<CustomField>
    <fullName>externalJobId__c</fullName>
    <label>externalJobId</label>
    <length>200</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Torc_Job_Opportunity__c/fields/status__c.field-meta.xml
<CustomField>
    <fullName>status__c</fullName>
    <label>Status</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Torc_Match__c/Torc_Match__c.object-meta.xml
<CustomObject>
    <label>Torc Match</label>
    <nameField>
        <displayFormat>M-{00000}</displayFormat>
        <label>Torc Match Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Torc Matches</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Torc_Match__c/fields/Contact__c.field-meta.xml
<CustomField>
    <fullName>Contact__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Contact</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Torc Matches</relationshipLabel>
    <relationshipName>Torc_Matches</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Torc_Match__c/fields/External_Id__c.field-meta.xml
<CustomField>
    <fullName>External_Id__c</fullName>
    <externalId>true</externalId>
    <label>External Id</label>
    <length>100</length>
    <required>true</required>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/Torc_Match__c/fields/jobOpportunityId__c.field-meta.xml
<CustomField>
    <fullName>jobOpportunityId__c</fullName>
    <label>Job Opportunity Id</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Torc_Match__c/fields/Sync_Request_Time__c.field-meta.xml
<CustomField>
    <fullName>Sync_Request_Time__c</fullName>
    <label>Sync Request Time</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/Torc_Match__c/fields/Torc_Job_Opportunity__c.field-meta.xml
<CustomField>
    <fullName>Torc_Job_Opportunity__c</fullName>
    <label>Torc Job Opportunity</label>
    <referenceTo>Torc_Job_Opportunity__c</referenceTo>
    <relationshipLabel>Torc Matches</relationshipLabel>
    <relationshipName>Torc_Matchs</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Torc_Match__c/fields/Torc_User_Ref__c.field-meta.xml
<CustomField>
    <fullName>Torc_User_Ref__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Torc User Ref</label>
    <referenceTo>Torc_User__c</referenceTo>
    <relationshipLabel>Torc Matches</relationshipLabel>
    <relationshipName>Torc_Matches</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Torc_Match__c/fields/User_Full_Name__c.field-meta.xml
<CustomField>
    <fullName>User_Full_Name__c</fullName>
    <formula>IF(Torc_Application__c&lt;&gt;NULL, Torc_Application__r.Torc_User__r.Full_Name__c, Torc_User_Ref__r.Full_Name__c)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>User Full Name</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Torc_Match__c/fields/userid__c.field-meta.xml
<CustomField>
    <fullName>userid__c</fullName>
    <label>userid</label>
    <length>80</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Torc_Rd1_Integration__c/Torc_Rd1_Integration__c.object-meta.xml
<CustomObject>
    <customSettingsType>Hierarchy</customSettingsType>
    <label>Torc Rd1 Integration</label>
</CustomObject>

force-app/main/default/objects/Torc_Rd1_Integration__c/fields/Sync_Enabled__c.field-meta.xml
<CustomField>
    <fullName>Sync_Enabled__c</fullName>
    <defaultValue>true</defaultValue>
    <label>Sync Enabled</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Torc_Rd1_Integration__c/fields/Torc_Search_URL__c.field-meta.xml
<CustomField>
    <fullName>Torc_Search_URL__c</fullName>
    <description>Torc Search URL</description>
    <inlineHelpText>Torc Search URL</inlineHelpText>
    <label>Torc Search URL</label>
    <type>Url</type>
</CustomField>

force-app/main/default/objects/Torc_User__c/Torc_User__c.object-meta.xml
<CustomObject>
    <label>Torc User</label>
    <nameField>
        <label>Torc User Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Torc Users</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Torc_User__c/fields/External_ID__c.field-meta.xml
<CustomField>
    <fullName>External_ID__c</fullName>
    <externalId>true</externalId>
    <label>External ID</label>
    <length>50</length>
    <required>true</required>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/classes/JobMatchController.cls
public without sharing class JobMatchController 
{    
    @AuraEnabled(cacheable=true)
    public static String getTorcJobId(String jobRecordId) 
    {
        TR1__Job__c job = [SELECT Torc_Id__c FROM TR1__Job__c WHERE Id = :jobRecordId LIMIT 1];
        return job.Torc_Id__c;
    }
    @AuraEnabled(cacheable=true)
    public static List<Torc_Match__c> getMatches(String torcId) 
    {
        TR1__Job__c trJob=[Select id, Torc_Id__c from TR1__Job__c where id=:torcId];
        
        List<Torc_Match__c> lst=[
            SELECT Id, User_Full_Name__c,torc_user_ref__r.external_id__c,Contact__c
            FROM Torc_Match__c
            WHERE jobOpportunityId__c = :trJob.Torc_Id__c AND 
            Status__c IN ('PRESHORTLISTED','TKSHORTLISTED','CZSHORTLISTED') 
            and torc_user_ref__c!=NULL and Delete_From_Platform__c = FALSE LIMIT 500
        ];
        
        Map<string,Contact> sSet=new Map<string,Contact>();
        for(Torc_Match__c rec:lst)
        {
            sSet.put(rec.torc_user_ref__r.external_id__c,null);
        }
        List<contact> lstContacts=new list<contact>();
        for(Contact c:[Select id,Name,torc_id__c from Contact where torc_id__c in :sSet.keyset()])
            sSet.put(c.torc_id__c,c);
        
        List<Torc_Match__c> finalList = new     List<Torc_Match__c>();
        for(Torc_Match__c rec:lst)
        {
            if(sSet.get(rec.torc_user_ref__r.external_id__c)!=NULL)
            {
                rec.Contact__c = sSet.get(rec.torc_user_ref__r.external_id__c).id;
                finalList.add(rec);
                if(finalList.size()>=20)
                    break;
            }        
        }
        system.debug(finalList.size());
        return finalList;
    }

    @AuraEnabled
    public static void addToList(List<Id> matchIds) 
    {
        /*System.debug('Selected Match IDs: ' + matchIds);
        List<Torc_Match__c>lstM = [Select Id, userId__c,jobOpportunityId__c,Status__c from Torc_Match__c where id in:matchIds];
        for(Torc_Match__c tm:lstM)
        {
            tm.Status__c='MATCHED';
        }
        torcRD1Integration.HardCallTorcmatchUpdate = true;
        update lstM;
        makematchesmatch(lstM);*/
    }
    /*public static void makematchesmatch(List<Torc_Match__c>lstM) 
    {
        List<Torc_API_Call__c> lstToUpsert=new List<Torc_API_Call__c>();
        for(Torc_Match__c tmatch:lstM)
        {
            Torc_API_Call__c rec=new Torc_API_Call__c(type__c='Torc_Match', Torc_Match__c =tMatch.id,Operation__c='UPDATE');
            rec.Body__c = JSON.serialize(tmatch);
            lstToUpsert.add(rec);
        }
        torcRD1Integration.runbatch(lstToUpsert);
    }*/
    @AuraEnabled(cacheable=true)
    public static Datetime getJobCreatedDate(String jobRecordId) 
    {
        //return datetime.now();
        TR1__Job__c job = [SELECT CreatedDate FROM TR1__Job__c WHERE Id = :jobRecordId LIMIT 1];
        return job.CreatedDate;
    }
    @AuraEnabled(cacheable=true)
    public static string getSearchURL(){
        Torc_Rd1_Integration__c rd1Instance = Torc_Rd1_Integration__c.getInstance();
        if (rd1Instance != null) {
            return rd1Instance.Torc_Search_URL__c;
        }
        return '';
    }
    @AuraEnabled(cacheable=true)
    public static String getOrgId() 
    {
        return UserInfo.getOrganizationId().substring(0, 15);
    }
    @AuraEnabled
    public static void setSyncTime(Id recordId) 
    {
        try
        {
            if(Torc_Rd1_Integration__c.getInstance().Sync_Enabled__c)
            {
                string s=recordId;
                if (recordId == null) throw new AuraHandledException('No recordId');
                if(s.left(3)=='003')
                    update new Contact(Id = recordId, sync_request_time__c = System.now(), applicable_for_torc_sync__c=true);
                else    
                {
                    TR1__Job__c j=[Select id, Torc_Id__c,Legacy_BH_Id__c,sync_request_time__c,applicable_for_torc_sync__c from TR1__Job__c where id=:recordId];
                    if(j.Torc_Id__c==NULL && j.Legacy_BH_Id__c!=NULL)
                    {
                        string stt=j.Legacy_BH_Id__c;
                        List<Torc_Job_opportunity__c> tj= [Select id, External_Id__c from Torc_Job_opportunity__c where externalJobId__c = :stt];
                        
                        if(tj.size()>0)
                        {
                            j.Torc_Id__c=tj[0].External_Id__c;
                            update j;
                            return;
                        }
                    }
                    update new tr1__Job__c(Id = recordId, sync_request_time__c = System.now(), applicable_for_torc_sync__c=true);
                }    
            }
        }
        catch(exception ex)
        {
            throw new AuraHandledException('Please edit and save the record first. Contact Admin if you continue see this error.' + ex.getMessage());
        }        
        
    }
}