force-app/main/default/objects/Torc_API_Call__c/Torc_API_Call__c.object-meta.xml
<CustomObject>
    <label>Torc API Call</label>
    <nameField>
        <displayFormat>CALL-{000000000}</displayFormat>
        <label>Sequence</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Torc API Calls</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Torc_API_Call__c/fields/Contact__c.field-meta.xml
<CustomField>
    <fullName>Contact__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Contact</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Torc API Calls</relationshipLabel>
    <relationshipName>Torc_API_Calls</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Torc_API_Call__c/fields/Operation__c.field-meta.xml
<CustomField>
    <fullName>Operation__c</fullName>
    <label>Operation</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>INSERT</fullName>
            </value>
            <value>
                <fullName>UPDATE</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Torc_API_Call__c/fields/Type__c.field-meta.xml
<CustomField>
    <fullName>Type__c</fullName>
    <label>Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Job</fullName>
            </value>
            <value>
                <fullName>User</fullName>
            </value>
            <value>
                <fullName>Match</fullName>
            </value>
            <value>
                <fullName>Torc_Match</fullName>
            </value>
            <value>
                <fullName>Resume</fullName>
            </value>
            <value>
                <fullName>Note</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Torc_Rd1_Integration__c/Torc_Rd1_Integration__c.object-meta.xml
<CustomObject>
    <customSettingsType>Hierarchy</customSettingsType>
    <label>Torc Rd1 Integration</label>
</CustomObject>

force-app/main/default/objects/Torc_Rd1_Integration__c/fields/Use_Flow_for_API_Call__c.field-meta.xml
<CustomField>
    <fullName>Use_Flow_for_API_Call__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Use Flow for API Call</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/classes/torcRd1OnetimeRd2Torc.cls
global class torcRd1OnetimeRd2Torc implements Database.Batchable<SObject>,Database.Stateful,Database.AllowsCallouts 
{
    global integer nextRun = 10;
    public static void process(string soql, integer delay, integer bSize)
    {
        torcRd1OnetimeRd2Torc myBatchObject = new torcRd1OnetimeRd2Torc(soql,delay); 
        Id batchId = Database.executeBatch(myBatchObject,bSize);
    }
    public string soqlQuery;
    public integer delaySec;
    Public torcRd1OnetimeRd2Torc(string soql,integer delay)
    {
        soqlQuery=soql;
        delaySec = delay;
    }
    global Database.QueryLocator start(Database.BatchableContext bc)
    { 
        return Database.getQueryLocator(soqlQuery);
    }

    global void execute(Database.BatchableContext bc, List<SObject> lstRecord) 
    {
        List<Torc_API_Call__c> lstTorcAPICalls=new List<Torc_API_Call__c>();
        for(sObject tb:lstrecord)
        {
            contact tj=(contact)tb;
            Torc_API_Call__c rec=new Torc_API_Call__c(type__c='User',Contact__c=tj.id,Operation__c='INSERT');
            rec.Body__c = JSON.serialize(tj);
            lstTorcAPICalls.add(rec);
        }
        upsert lstTorcAPICalls;
        if(!Torc_Rd1_Integration__c.getInstance().Use_Flow_for_API_Call__c)
        {
            set<id> recids=new set<id>();
            for(Torc_API_Call__c r:lstTorcAPICalls)
                recIds.add(r.id);
            torcRD1Integrationbatch runSkipped=new torcRD1Integrationbatch(recids);
            Datetime runTime = datetime.Now().addseconds(nextRun);
            nextRun +=delaySec;
            String cronExp = String.format('{0} {1} {2} {3} {4} ? {5}', new List<String>{
                String.valueOf(runTime.second()),
                String.valueOf(runTime.minute()),
                String.valueOf(runTime.hour()),
                String.valueOf(runTime.day()),
                String.valueOf(runTime.month()),
                String.valueOf(runTime.year())
            });    
            System.schedule('torcIntegrate-'+userInfo.getuserId()+runTime.ToString(), cronExp, runSkipped);  
        }     
    }
    global void finish(Database.BatchableContext bc)
    {
    }
}