force-app/main/default/objects/Api_Url__c/Api_Url__c.object-meta.xml
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <label>Api_Url</label>
</CustomObject>

force-app/main/default/objects/Api_Url__c/fields/Key__c.field-meta.xml
<CustomField>
    <fullName>Key__c</fullName>
    <label>Key</label>
    <length>50</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Api_Url__c/fields/Url__c.field-meta.xml
<CustomField>
    <fullName>Url__c</fullName>
    <label>Url</label>
    <length>200</length>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/ESBSelector.cls
public with sharing class ESBSelector {
    public static string getEsbUrl(){
        User u = [Select Opco__c From User Where Id = :UserInfo.getUserId()][0];
        system.debug(u.Opco__c);
        switch on u.Opco__c {
            when 'France' {
                return Api_Url__c.getValues('ESB_FR').Url__c;
            }
            when else {
                return Api_Url__c.getValues('ESB_BE').Url__c;
            }
        }
    }
    
    public static string getApiKey(){
        User u = [Select Opco__c From User Where Id = :UserInfo.getUserId()][0];
        system.debug(u.Opco__c);
        switch on u.Opco__c {
            when 'France' {
                return Api_Url__c.getValues('ESB_FR').Key__c;
            }
            when else {
                return Api_Url__c.getValues('ESB_BE').Key__c;
            }
        }
    }
    
    public static string getEsbUrlOpp(string ownerId){
        User u = [Select Opco__c From User Where Id = :ownerId][0];
        system.debug(u.Opco__c);
        switch on u.Opco__c {
            when 'France' {
                return Api_Url__c.getValues('ESB_FR').Url__c;
            }
            when else {
                return Api_Url__c.getValues('ESB_BE').Url__c;
            }
        }
    }
    public static string getApiKeyOpp(string ownerId){
        User u = [Select Opco__c From User Where Id = :ownerId][0];
        system.debug(u.Opco__c);
        switch on u.Opco__c {
            when 'France' {
                return Api_Url__c.getValues('ESB_FR').Key__c;
            }
            when else {
                return Api_Url__c.getValues('ESB_BE').Key__c;
            }
        }
    }
    public static String getEsbUrlForOpco(String opco) {
        if (opco != null) {
            if (opco.equalsIgnoreCase('France')) {
                return Api_Url__c.getValues('ESB_FR').Url__c;
                
            } 
            else{
                return Api_Url__c.getValues('ESB_BE').Url__c;
            }
        }
        
        return null;
    }
    
}