force-app/main/default/objects/Trolley_Recipient__c/Trolley_Recipient__c.object-meta.xml
<CustomObject>
    <label>Trolley Recipient</label>
    <nameField>
        <label>Trolley Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Trolley Recipients</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Trolley_Recipient__c/fields/Active_Payment_Account_ID__c.field-meta.xml
<CustomField>
    <fullName>Active_Payment_Account_ID__c</fullName>
    <label>Active Payment Account ID</label>
    <length>80</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Trolley_Recipient__c/fields/Estimated_Fee__c.field-meta.xml
<CustomField>
    <fullName>Estimated_Fee__c</fullName>
    <label>Estimated Fee</label>
    <precision>7</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Trolley_Recipient__c/fields/external_Id__c.field-meta.xml
<CustomField>
    <fullName>external_Id__c</fullName>
    <externalId>true</externalId>
    <label>external Id</label>
    <length>80</length>
    <required>true</required>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/Trolley_Recipient__c/fields/First_Name__c.field-meta.xml
<CustomField>
    <fullName>First_Name__c</fullName>
    <label>First Name</label>
    <length>150</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Trolley_Recipient__c/fields/Last_Name__c.field-meta.xml
<CustomField>
    <fullName>Last_Name__c</fullName>
    <label>Last Name</label>
    <length>150</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Trolley_Recipient__c/fields/Payout_Method__c.field-meta.xml
<CustomField>
    <fullName>Payout_Method__c</fullName>
    <label>Payout Method</label>
    <length>40</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Trolley_Recipient__c/fields/referenceId__c.field-meta.xml
<CustomField>
    <fullName>referenceId__c</fullName>
    <label>referenceId</label>
    <length>80</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Trolley_Recipient__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <length>80</length>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/TrolleyReceipientQueue.cls
Public class TrolleyReceipientQueue implements Queueable, database.AllowsCallouts
{
    public static void runProcess(boolean isTest)
    {
        System.enqueueJob(new TrolleyReceipientQueue(1,isTest));
    }
    public integer pageNumber;
    public boolean istestRun;
    public string singleRecId;
    public TrolleyReceipientQueue(integer pgN,boolean isTest)
    {
        pageNumber=pgN;
        istestRun = istest;
        singleRecId=null;
    }
    public TrolleyReceipientQueue(integer pgN,boolean isTest,string singleRecId1)
    {
        pageNumber=pgN;
        istestRun = istest;
        singleRecId= singleRecId1;
    }
    public void execute(QueueableContext context) 
    {
        if(test.isRunningTest())
            QBOpportunitySetup.QBAPITestOperation = 'RETRIVEREC';
            
        string reqpath = 'recipients';
        if(singleRecId!=NULL)
            reqpath += '/'+singleRecId;
        
        reqpath += '?page='+pageNumber+'&pageSize='+'50';
        
        string body = TrolleyBase.callAPI('GET',null,reqpath);
        JSONParser jp = JSON.createParser(body);
        TrolleyService.T_recipients t = (TrolleyService.T_recipients)jp.readValueAs(TrolleyService.T_recipients.class);
        
        
        if(singleRecId!=NULL)
        {
            t.recipients = new List<TrolleyService.T_recipient>();
            t.recipients.add(t.recipient);
        }
        system.debug(body);        
        system.debug(pageNumber+'---'+t.recipients.size());

        List<TrolleyService.T_recipient> lst = t.recipients;
        List<Trolley_Recipient__c> upsertList=new List<Trolley_Recipient__c>();
        for(TrolleyService.T_recipient trollyObj:lst)
        {
            upsertList.add(setupRecord(trollyObj));
        }
        upsert upsertList external_Id__c;
        
        if(t.recipients.size()>=50)
        {
            TrolleyReceipientQueue aq = new TrolleyReceipientQueue(pageNumber+1,istestRun);
            if(!istestRun)
                System.enqueueJob(aq);
        }        
    }
    public static Trolley_Recipient__c setupRecord(TrolleyService.T_recipient trollyObj)
    {
        Trolley_Recipient__c rec= new Trolley_Recipient__c();
        rec.external_Id__c = trollyObj.id;
        rec.referenceId__c = trollyObj.referenceId;
        rec.Name = trollyObj.name==NULL?'':trollyObj.name.left(80);
        rec.Last_Name__c = trollyObj.LastName;
        rec.First_Name__c = trollyObj.Firstname;
        rec.Payout_method__c = trollyObj.payoutMethod;
        rec.Status__c = trollyObj.status;
        rec.Country__c = (trollyObj.address!=NULL && trollyObj.address.country!=NULL)?trollyObj.address.country:NULL;
        rec.estimated_Fee__c = trollyObj.estimatedFees==Null?0:Decimal.valueOf(trollyObj.estimatedFees);
        if(trollyObj.accounts!=NULL && trollyObj.accounts.size()>0)
        {
            for(TrolleyService.T_account act:trollyObj.accounts)
            {
                if(Act.primary==true)
                    rec.Active_Payment_Account_ID__c = act.id;
            }
        }
        return rec;
    }    
}