force-app/main/default/objects/Non_Torc_User__c/Non_Torc_User__c.object-meta.xml
<CustomObject>
    <label>Non Torc User</label>
    <nameField>
        <label>Non Torc User Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Non Torc Users</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Non_Torc_User__c/fields/Quick_Books_vendor_Id__c.field-meta.xml
<CustomField>
    <fullName>Quick_Books_vendor_Id__c</fullName>
    <label>Quick Books vendor Id</label>
    <length>80</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Non_Torc_User__c/fields/Quickbooks_Vendor__c.field-meta.xml
<CustomField>
    <fullName>Quickbooks_Vendor__c</fullName>
    <label>Quickbooks Vendor</label>
    <length>80</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Non_Torc_User__c/fields/Trolley_Creation_Requested__c.field-meta.xml
<CustomField>
    <fullName>Trolley_Creation_Requested__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Trolley Creation Requested</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/QB_API_Call__c/QB_API_Call__c.object-meta.xml
<CustomObject>
    <label>QB API Call</label>
    <nameField>
        <label>Type</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>QB API Calls</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/QB_API_Call__c/fields/Delete__c.field-meta.xml
<CustomField>
    <fullName>Delete__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Delete?</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/QB_API_Call__c/fields/Group__c.field-meta.xml
<CustomField>
    <fullName>Group__c</fullName>
    <label>Group</label>
    <length>70</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/QB_API_Call__c/fields/Non_Torc_User__c.field-meta.xml
<CustomField>
    <fullName>Non_Torc_User__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Non Torc User</label>
    <referenceTo>Non_Torc_User__c</referenceTo>
    <relationshipLabel>QB API Calls</relationshipLabel>
    <relationshipName>QB_API_Calls</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/QB_API_Call__c/fields/Sequence__c.field-meta.xml
<CustomField>
    <fullName>Sequence__c</fullName>
    <label>Sequence</label>
    <type>AutoNumber</type>
</CustomField>

force-app/main/default/classes/QBAPICallBatch.cls
global class QBAPICallBatch implements Database.Batchable<SObject>,Database.Stateful,Database.AllowsCallouts 
{
    public static void processNow(string groupName)
    {
        QBAPICallBatch myBatchObject = new QBAPICallBatch(groupName); 
        Id batchId = Database.executeBatch(myBatchObject,10);
    }
    public string groupNameToUse;
    Public QBAPICallBatch(string groupName)
    {
        groupNameToUse = groupName;
    }
    global Database.QueryLocator start( Database.BatchableContext bc )
    { 
        QB_Authentication authentication = new QB_Authentication();
        authentication.initializeToken();
        authentication.persistTokenInDb();
        string s = 'Select ID, Name, Non_Torc_user__c, Sequence__c, Input__c,Output__c, Group__c,Processed__c,Delete__c FROM QB_API_Call__c WHERE Processed__c=FALSE AND Group__c=:groupNameToUse';
        return Database.getQueryLocator(s);
    }

    global void execute(Database.BatchableContext bc, List<SObject> lstRecord) 
    {
        QBHttpService qb = QBAccountingService.getQBHttpService();
        map<string,Non_Torc_user__c> mapnonTorc = new map<string,Non_Torc_user__c>();
        for(sObject tb:lstrecord)
        {
            QB_API_Call__c rec=(QB_API_Call__c)tb;
            string input = rec.Input__c;
            
            if(rec.Name=='bill')
                input = input.replace('[BILL_NUMBER_SFDC]',rec.Sequence__c);
            
            string recName = rec.name;
            if(rec.Delete__c)
                recName +='?operation=delete';
            try
            {
                if(rec.Name=='NonTorc-VendorQB')
                {
                    JSONParser jp = JSON.createParser((rec.Input__c));
                    QBAccountingService.QBVendor qbV = (QBAccountingService.QBVendor) jp.readValueAs(QBAccountingService.QBVendor.class);
                    qbV = QBAccountingService.createVendorinQb(qbV);
                    if(qbV!=NULL)
                    {
                        if(mapnonTorc.get(rec.Non_Torc_user__c)==NULL)
                            mapnonTorc.put(rec.Non_Torc_user__c,new Non_Torc_user__c(id=rec.Non_Torc_user__c));
                        Non_Torc_user__c tu= mapnonTorc.get(rec.Non_Torc_user__c);
                        tu.Quick_Books_vendor_Id__c = qbV.Id;
                        tu.Quickbooks_Vendor__c = qbV.DisplayName;
                    }
                }
                else if(rec.Name=='NonTorc-VendorTrolley')
                {
                    JSONParser jp = JSON.createParser((rec.Input__c));
                    TrolleyService.T_recipient tRec = (TrolleyService.T_recipient) jp.readValueAs(TrolleyService.T_recipient.class);
                    TrolleyService.createRecipient(tRec);
                    if(mapnonTorc.get(rec.Non_Torc_user__c)==NULL)
                        mapnonTorc.put(rec.Non_Torc_user__c,new Non_Torc_user__c(id=rec.Non_Torc_user__c));
                    Non_Torc_user__c tu= mapnonTorc.get(rec.Non_Torc_user__c);
                    tu.Trolley_Creation_Requested__c = true;
                }
                else
                {
                    rec.Output__c = qb.postObject(recName,input);
                }    
                rec.Processed__c = true;
            }
            catch(exception ex)
            {
                system.debug(ex);
            }
        }
        if(mapnonTorc.keyset().size()>0)
        {
            update mapnonTorc.values();
        }
        update lstRecord;
    }
  global void finish(Database.BatchableContext bc)
  {
  }
}