force-app/main/default/objects/Non_Torc_User__c/Non_Torc_User__c.object-meta.xml
<CustomObject>
    <label>Non Torc User</label>
    <nameField>
        <label>Non Torc User Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Non Torc Users</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Non_Torc_User__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Non Torc Users</relationshipLabel>
    <relationshipName>Non_Torc_Users</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Non_Torc_User__c/fields/Contact__c.field-meta.xml
<CustomField>
    <fullName>Contact__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Contact</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Non Torc Users</relationshipLabel>
    <relationshipName>Non_Torc_Users</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Non_Torc_User__c/fields/Default_Monthly_Rate__c.field-meta.xml
<CustomField>
    <fullName>Default_Monthly_Rate__c</fullName>
    <label>Default Monthly Rate</label>
    <precision>10</precision>
    <required>true</required>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Non_Torc_User__c/fields/Engagement_Months__c.field-meta.xml
<CustomField>
    <fullName>Engagement_Months__c</fullName>
    <defaultValue>12</defaultValue>
    <label>Engagement Months</label>
    <precision>3</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Non_Torc_User__c/fields/Family_Name__c.field-meta.xml
<CustomField>
    <fullName>Family_Name__c</fullName>
    <label>Family Name</label>
    <length>80</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Non_Torc_User__c/fields/First_Month__c.field-meta.xml
<CustomField>
    <fullName>First_Month__c</fullName>
    <label>Engagement Start Date</label>
    <required>true</required>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Non_Torc_User__c/fields/Given_Name__c.field-meta.xml
<CustomField>
    <fullName>Given_Name__c</fullName>
    <label>Given Name</label>
    <length>80</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Non_Torc_User__c/fields/Monthly_USD_Expense__c.field-meta.xml
<CustomField>
    <fullName>Monthly_USD_Expense__c</fullName>
    <label>Monthly USD Expense</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Non_Torc_User__c/fields/Official_Email__c.field-meta.xml
<CustomField>
    <fullName>Official_Email__c</fullName>
    <label>Official Email</label>
    <type>Email</type>
</CustomField>

force-app/main/default/objects/Non_Torc_User__c/fields/Payment_Start_Date__c.field-meta.xml
<CustomField>
    <fullName>Payment_Start_Date__c</fullName>
    <label>Payment Start Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Non_Torc_User__c/fields/Position__c.field-meta.xml
<CustomField>
    <fullName>Position__c</fullName>
    <label>Position</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Data Developer</fullName>
            </value>
            <value>
                <fullName>Delivery Manager</fullName>
            </value>
            <value>
                <fullName>Engineering Developer</fullName>
            </value>
            <value>
                <fullName>Lead Mobile developer</fullName>
            </value>
            <value>
                <fullName>Location Manager</fullName>
            </value>
            <value>
                <fullName>Machine Learning Senior</fullName>
            </value>
            <value>
                <fullName>Mobile Developer</fullName>
            </value>
            <value>
                <fullName>Project Manager</fullName>
            </value>
            <value>
                <fullName>Quality Assurance</fullName>
            </value>
            <value>
                <fullName>Talent Acquisition Specialist</fullName>
            </value>
            <value>
                <fullName>UX/UI Designer</fullName>
            </value>
            <value>
                <fullName>Site Reliability Engineering</fullName>
            </value>
            <value>
                <fullName>Firmware</fullName>
            </value>
            <value>
                <fullName>Cybersecurity</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/loadQubikaData.cls
Public class loadQubikaData
{
    
    Public List<googleAPI.rowCls> lstData{get;set;}
    Public string spreadsheetId{get;set;}
    Public string sheetName{get;set;}
    Public string sheetRange{get;set;}
    Public Account act{get;set;}
    public loadQubikaData(ApexPages.StandardController controller)
    {
        act=(Account) controller.getRecord();
        spreadsheetId = '1TyrA8PGFB4cANIZBFVd39qMIpEbvrg64cYIZQF_EZ-Q';
        sheetName = 'Sheet1';
        sheetRange = 'A1:J';
        lstData = new List<googleAPI.rowCls>();
    }
    public void loaddata()
    {
        lstData.clear();
        string error = googleAPI.GetQubikaDataFromSpreadsheet(spreadsheetId,sheetName,sheetRange,lstData);
        if(error!='' && error!=null)
        {
            ApexPages.addmessage(new ApexPages.message(ApexPages.severity.Error,error));
            return;
        }
        map<string,googleAPI.rowCls> emails=new map<string,googleAPI.rowCls>();
        for(googleAPI.rowCls r:lstData)
        {
            emails.put(r.OfficialEmail.toLowerCase().trim(),r);
        }
        for(Non_Torc_user__c ntr:[Select Id, Name,  Payment_Start_Date__c, Given_Name__c, Family_Name__c, Email__c, Monthly_USD_Expense__c, 
                                        Account__c, Default_Monthly_Rate__c, 
                                        First_Month__c, Engagement_Months__c, 
                                        Contact__c, Official_Email__c, 
                                        Termination_Date__c, Country__c, Position__c 
                                        FROM Non_Torc_user__c where Official_Email__c in:emails.keyset()])
        {
            emails.get(ntr.Official_Email__c.toLowercase()).user = ntr;
        }
        for(googleAPI.rowCls r:lstData)
        {
            if(r.user==NULL)
            {
               r.user=new  Non_Torc_user__c(Account__c = act.id);
            }
            r.editData();
        }                                        
        
    }
    public void updateData()
    {
        List<Non_Torc_user__c> l=new List<Non_Torc_user__c>();
        for(googleAPI.rowCls r:lstData)
        {
            if(r.chk)
                l.add(r.user);
        }
        if(l.size()>0)
            Upsert l;
    }
}