force-app/main/default/objects/Non_Torc_Payment__c/Non_Torc_Payment__c.object-meta.xml
<CustomObject>
    <label>Non Torc Payment</label>
    <nameField>
        <label>Payment Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Non Torc Payments</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Non_Torc_Payment__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Non Torc Payments</relationshipLabel>
    <relationshipName>Non_Torc_Payments</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Non_Torc_Payment__c/fields/Bank_Fee__c.field-meta.xml
<CustomField>
    <fullName>Bank_Fee__c</fullName>
    <label>Bank Fee</label>
    <precision>12</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Non_Torc_Payment__c/fields/For_Month__c.field-meta.xml
<CustomField>
    <fullName>For_Month__c</fullName>
    <label>For Month</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Non_Torc_Payment__c/fields/Non_Torc_User__c.field-meta.xml
<CustomField>
    <fullName>Non_Torc_User__c</fullName>
    <label>Non Torc User</label>
    <referenceTo>Non_Torc_User__c</referenceTo>
    <relationshipLabel>Non Torc Payments</relationshipLabel>
    <relationshipName>Non_Torc_Payments</relationshipName>
    <relationshipOrder>1</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Non_Torc_Payment__c/fields/Opportunity__c.field-meta.xml
<CustomField>
    <fullName>Opportunity__c</fullName>
    <label>Opportunity</label>
    <referenceTo>Opportunity</referenceTo>
    <relationshipLabel>Non Torc Payments</relationshipLabel>
    <relationshipName>Non_Torc_Payments</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Non_Torc_Payment__c/fields/Opportunity_Product__c.field-meta.xml
<CustomField>
    <fullName>Opportunity_Product__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Opportunity Product</label>
    <referenceTo>OpportunityLineItem</referenceTo>
    <relationshipLabel>Non Torc Payments</relationshipLabel>
    <relationshipName>Non_Torc_Payments</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Non_Torc_Payment__c/fields/Payment_Created__c.field-meta.xml
<CustomField>
    <fullName>Payment_Created__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Payment Created</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Non_Torc_Payment__c/fields/Torc_Fee__c.field-meta.xml
<CustomField>
    <fullName>Torc_Fee__c</fullName>
    <label>Torc Fee</label>
    <precision>12</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Non_Torc_User__c/Non_Torc_User__c.object-meta.xml
<CustomObject>
    <label>Non Torc User</label>
    <nameField>
        <label>Non Torc User Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Non Torc Users</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Non_Torc_User__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Non Torc Users</relationshipLabel>
    <relationshipName>Non_Torc_Users</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Non_Torc_User__c/fields/Default_Monthly_Rate__c.field-meta.xml
<CustomField>
    <fullName>Default_Monthly_Rate__c</fullName>
    <label>Default Monthly Rate</label>
    <precision>10</precision>
    <required>true</required>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Non_Torc_User__c/fields/Docusign_Status__c.field-meta.xml
<CustomField>
    <fullName>Docusign_Status__c</fullName>
    <formula>IF( Explicit_Docusign_Mark_Complete__c ,&apos;Completed&apos;,
IF( Latest_DocuSign_Status__c = NULL,&apos;Not Sent&apos;,  Latest_DocuSign_Status__r.dfsle__Status__c ))</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Docusign Status</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Non_Torc_User__c/fields/Monthly_USD_Expense__c.field-meta.xml
<CustomField>
    <fullName>Monthly_USD_Expense__c</fullName>
    <label>Monthly USD Expense</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Non_Torc_User__c/fields/Official_Email__c.field-meta.xml
<CustomField>
    <fullName>Official_Email__c</fullName>
    <label>Official Email</label>
    <type>Email</type>
</CustomField>

force-app/main/default/objects/Non_Torc_User__c/fields/Trolley_Recipient__c.field-meta.xml
<CustomField>
    <fullName>Trolley_Recipient__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Trolley Recipient</label>
    <referenceTo>Trolley_Recipient__c</referenceTo>
    <relationshipLabel>Non Torc Users</relationshipLabel>
    <relationshipName>Non_Torc_Users</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Non_Torc_User__c/fields/Trolley_Status__c.field-meta.xml
<CustomField>
    <fullName>Trolley_Status__c</fullName>
    <formula>IF( Trolley_Recipient__c = NULL,&apos;Not Created&apos;, Trolley_Recipient__r.Status__c )</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Payment Profile</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Trolley_Recipient__c/Trolley_Recipient__c.object-meta.xml
<CustomObject>
    <label>Trolley Recipient</label>
    <nameField>
        <label>Trolley Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Trolley Recipients</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Trolley_Recipient__c/fields/Estimated_Fee__c.field-meta.xml
<CustomField>
    <fullName>Estimated_Fee__c</fullName>
    <label>Estimated Fee</label>
    <precision>7</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Trolley_Recipient__c/fields/Non_Torc_User__c.field-meta.xml
<CustomField>
    <fullName>Non_Torc_User__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Non Torc User</label>
    <referenceTo>Non_Torc_User__c</referenceTo>
    <relationshipLabel>Trolley Recipients</relationshipLabel>
    <relationshipName>Trolley_Recipients</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Trolley_Recipient__c/fields/Payout_Method__c.field-meta.xml
<CustomField>
    <fullName>Payout_Method__c</fullName>
    <label>Payout Method</label>
    <length>40</length>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/nonTorcpayment.cls
Public class nonTorcpayment
{
    public opportunity opp{get;set;}
    public opportunityLineItem oppLineItem{get;set;}
    Public List<googleAPI.paymentCls> lstData{get;set;}
    Public string spreadsheetId{get;set;}
    Public string sheetName{get;set;}
    Public string sheetRange{get;set;}
    Public Account act{get;set;}
    public boolean isError{get;set;}
    public string warningMessage{get;set;}
    public decimal getTotalbankFee()
    {
        Decimal paypalAmount = 0;
        Decimal amt=0;
        for(googleAPI.paymentCls r:lstData)
        {
            if(r.chk)
            {
                amt +=r.payRec.Bank_fee__c;
                if(r.isPaypal)
                {
                    paypalAmount += r.total;
                }    
            }    
        }
        if(paypalAmount >=1000)
            amt +=20;
        else
            amt +=(paypalAmount*0.02);    
        return amt;
    }
    
    public decimal getTotalTorcFee()
    {
        Decimal amt=0;
        for(googleAPI.paymentCls r:lstData)
        {
            if(r.chk)
                amt +=r.payRec.Torc_fee__c;
        }
        return amt;
    }
    public void dummyCall(){}
    public string showRowsType{get;set;}
    public List<SelectOption> getShowTypes()
    {
        List<SelectOption> ifPicklist = new List<SelectOption> ();
        ifPicklist.add(new SelectOption('All','All'));
        ifPicklist.add(new SelectOption('Error','Error'));
        ifPicklist.add(new SelectOption('Non-Error','Non-Error'));
        return ifPickList;
    }
    public List<googleAPI.paymentCls> getshowableRows()
    {
        List<googleAPI.paymentCls> l=new List<googleAPI.paymentCls>();
        for(googleAPI.paymentCls dr:lstData)
        {
            if(showRowsType=='All' 
                || (showRowsType=='Error' && dr.getIsError()) 
                || (showRowsType=='Non-Error' && dr.getIsError()==FALSE))
            {
                l.add(dr);
            } 
        }
        return l;
    } 
    public nonTorcpayment(ApexPages.StandardController controller)
    {
        showRowsType='All';
        warningMessage='';
        isError=false;
        opp = (Opportunity)controller.getRecord();
        opp = [Select Id, Name, Closedate,StageName, AccountId,Account.Name,
                (Select ID ,Engagement_Start_Date__c, Customer_Hourly_Bill_Rate__c ,Unitprice,TotalPrice
                                    FROM OpportunityLineItems where Product2.name='Transaction Fee'),
                (Select ID from Non_Torc_payments__r where Payment_Created__c=TRUE LIMIT 1)                                    
               FROM Opportunity Where id=:opp.id];
        act = opp.Account;
        spreadsheetId = '1wPEmQR-YjIeh2Jqkj4Nx7rsWO2qn8ASSFg9Ri6SDNAI';
        sheetName = 'Sheet2';
        sheetRange = 'A1:D';
        lstData = new List<googleAPI.paymentCls>();       
        /*if(opp.OpportunityLineItems.size()!=1)
        {
             ApexPages.addmessage(new ApexPages.message(ApexPages.severity.Error,'Error:There should be one and only one lineitem with product "Transaction fee" on this opportunity.'));
             isError = true;
             return;
        }*/
        if(opp.Non_Torc_payments__r.size()>0)
        {
             ApexPages.addmessage(new ApexPages.message(ApexPages.severity.Error,'Error:There are already some payments marked paid. Please create a new opportunity now.'));
             isError = true;
             return;
        }
        if([Select Id from Non_Torc_payment__c where Opportunity__c=:opp.id LIMIT 1].size()>0)
        {
            warningMessage = 'There are already payments created for this month. Nothing is marked paid yet. So this process will delete existing records.';
        }
        if(opp.OpportunityLineItems.size()==0)
        {
            id priceBookID = [Select ID from priceBook2 where Name='Standard Price Book'].Id;
            PricebookEntry pbe = [Select Id, IsActive,Product2Id, Product2.Name, Product2.ProductCode,Product2.Description, UnitPrice
                                from PricebookEntry
                                where Pricebook2Id=:priceBookID
                                AND Product2.Name='Transaction Fee'];
            Date dt = Date.newInstance(Opp.Closedate.year(),Opp.Closedate.Month(),1);
            oppLineItem=new opportunityLineItem(OpportunityId=opp.id,
                                                Engagement_Start_Date__c=dt,
                                                Quantity=1,
                                                Product2Id = pbe.Product2Id,priceBookEntryID= pbe.id,
                                                Product_Type__c = 'Transaction Fee',
                                                Hours_Week__c=1,
                                                Engagement_End_Date__c = dt.adddays(7),
                                                Engagement_Duration_weeks__c=1,
                                                Time_Commitment__c = 'HALFTIME',
                                                Talent_Hourly_Pay_Rate__c=0
                                                );
                                        
        }   
        else
            oppLineItem = opp.OpportunityLineItems[0];
    }
    public void loaddata()
    {
        lstData.clear();
        string error = googleAPI.GetQubikaPaymentFromSpreadsheet(spreadsheetId,sheetName,sheetRange,lstData);
        if(error!='' && error!=null)
        {
            ApexPages.addmessage(new ApexPages.message(ApexPages.severity.Error,error));
            return;
        }
        map<string,googleAPI.paymentCls> emails=new map<string,googleAPI.paymentCls>();
        for(googleAPI.paymentCls r:lstData)
        {
            emails.put(r.OfficialEmail.toLowerCase().trim(),r);
        }
        for(Non_Torc_user__c ntr:[Select Id, Name, Monthly_USD_Expense__c, Default_Monthly_Rate__c, Official_Email__c, 
                                        Trolley_recipient__r.Estimated_fee__c,Trolley_Status__c,Docusign_Status__c, Trolley_recipient__r.Payout_Method__c
                                        FROM Non_Torc_user__c where Official_Email__c in:emails.keyset() AND account__c =: opp.AccountId])
        {
            emails.get(ntr.Official_Email__c.toLowercase()).setUser(ntr);
        }
        for(googleAPI.paymentCls r:lstData)
        {
            r.editData(opp,oppLineItem);
        }                                        
    }
    public Pagereference updateData()
    {
        decimal tf=0;
        for(List< Non_Torc_payment__c >l:[Select id from Non_Torc_payment__c where Opportunity__c=:opp.id])
            delete l;
        List< Non_Torc_payment__c >newList=new List< Non_Torc_payment__c >();    
        for(googleAPI.paymentCls r:lstData)
        {
            if(r.chk)
            {
                tf +=r.payRec.Torc_fee__c;
                newList.add(r.payRec);
            }    
        }
        oppLineItem.UnitPrice = tf;
        oppLineItem.Bank_fee__c = getTotalbankFee();
        oppLineItem.Customer_Hourly_Bill_Rate__c = tf;
        upsert oppLineItem;
        for(Non_Torc_payment__c a:newlist)
        {
            a.Opportunity_Product__c = oppLineItem.id;
            a.Opportunity__c = opp.id;
            a.Account__c = opp.AccountId;
            a.For_Month__c = oppLineItem.Engagement_Start_Date__c;
        }
        insert newList;
        return new Pagereference('/'+opp.id);
    }
}