force-app/main/default/objects/Placement__c/Placement__c.object-meta.xml
<CustomObject>
    <label>Torc Placement</label>
    <nameField>
        <label>Placement Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Torc Placements</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Placement__c/fields/First_Working_Day__c.field-meta.xml
<CustomField>
    <fullName>First_Working_Day__c</fullName>
    <label>First Working Day</label>
    <summarizedField>Placement_Forecast__c.Engagement_Start__c</summarizedField>
    <summaryFilterItems>
        <field>Placement_Forecast__c.Engagement_Start__c</field>
        <operation>notEqual</operation>
        <value></value>
    </summaryFilterItems>
    <summaryFilterItems>
        <field>Placement_Forecast__c.Default_Hours_Week__c</field>
        <operation>greaterThan</operation>
        <value>0</value>
    </summaryFilterItems>
    <summaryForeignKey>Placement_Forecast__c.Placement__c</summaryForeignKey>
    <summaryOperation>min</summaryOperation>
    <type>Summary</type>
</CustomField>

force-app/main/default/objects/Placement__c/fields/Last_Working_Day__c.field-meta.xml
<CustomField>
    <fullName>Last_Working_Day__c</fullName>
    <label>Last Working Day</label>
    <summarizedField>Placement_Forecast__c.Engagement_End__c</summarizedField>
    <summaryFilterItems>
        <field>Placement_Forecast__c.Engagement_End__c</field>
        <operation>notEqual</operation>
        <value></value>
    </summaryFilterItems>
    <summaryFilterItems>
        <field>Placement_Forecast__c.Default_Hours_Week__c</field>
        <operation>greaterThan</operation>
        <value>0</value>
    </summaryFilterItems>
    <summaryForeignKey>Placement_Forecast__c.Placement__c</summaryForeignKey>
    <summaryOperation>max</summaryOperation>
    <type>Summary</type>
</CustomField>

force-app/main/default/objects/Placement__c/fields/Torc_User__c.field-meta.xml
<CustomField>
    <fullName>Torc_User__c</fullName>
    <label>Torc User</label>
    <referenceTo>Torc_User__c</referenceTo>
    <relationshipName>Placements</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Referral_Bonus__c/Referral_Bonus__c.object-meta.xml
<CustomObject>
    <label>Referral Bonus</label>
    <nameField>
        <displayFormat>RB-{00000}</displayFormat>
        <label>Referral Bonus Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Referral Bonus</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Referral_Bonus__c/fields/Payment_Week__c.field-meta.xml
<CustomField>
    <fullName>Payment_Week__c</fullName>
    <label>Payment Week</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Referral_Bonus__c/fields/Referral_Payment_Created__c.field-meta.xml
<CustomField>
    <fullName>Referral_Payment_Created__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Referral Payment Created</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Referral_Bonus__c/fields/Referred_By__c.field-meta.xml
<CustomField>
    <fullName>Referred_By__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Referred By</label>
    <referenceTo>Torc_User__c</referenceTo>
    <relationshipLabel>Referral_Bonus(Referred By)</relationshipLabel>
    <relationshipName>Referral_Bonus1</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Referral_Bonus__c/fields/Referred_To__c.field-meta.xml
<CustomField>
    <fullName>Referred_To__c</fullName>
    <label>Referred To</label>
    <referenceTo>Torc_User__c</referenceTo>
    <relationshipLabel>Referral Bonus (Referred To)</relationshipLabel>
    <relationshipName>Referral_Bonus</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Referral_Bonus__c/fields/Referrer_Payment_Created__c.field-meta.xml
<CustomField>
    <fullName>Referrer_Payment_Created__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Referrer Payment Created</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Torc_User__c/Torc_User__c.object-meta.xml
<CustomObject>
    <label>Torc User</label>
    <nameField>
        <label>Torc User Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Torc Users</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Torc_User__c/fields/Exclude_Referral_Bonus__c.field-meta.xml
<CustomField>
    <fullName>Exclude_Referral_Bonus__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Is Torc?</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Torc_User__c/fields/Exclude_Referrer_Bonus__c.field-meta.xml
<CustomField>
    <fullName>Exclude_Referrer_Bonus__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Exclude Referrer Bonus</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Torc_User__c/fields/First_Working_Day__c.field-meta.xml
<CustomField>
    <fullName>First_Working_Day__c</fullName>
    <label>First Working Day</label>
    <summarizedField>Placement__c.First_Working_Day__c</summarizedField>
    <summaryForeignKey>Placement__c.Torc_User__c</summaryForeignKey>
    <summaryOperation>min</summaryOperation>
    <type>Summary</type>
</CustomField>

force-app/main/default/objects/Torc_User__c/fields/Referrer__c.field-meta.xml
<CustomField>
    <fullName>Referrer__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Referrer</label>
    <referenceTo>Torc_User__c</referenceTo>
    <relationshipLabel>Torc Users</relationshipLabel>
    <relationshipName>Torc_Users</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/classes/ReferralBonus.cls
Public class ReferralBonus
{
    public static void setupreferralBonus(set<id> userId)
    {
        List<Torc_User__c>lsttu=[Select ID, Referrer__c, Exclude_Referral_Bonus__c, Referrer__r.Exclude_Referrer_Bonus__c,
                            (Select Payment_Week__c, Referred_By__c, referral_Payment_Created__c, referrer_Payment_Created__c 
                                from Referral_Bonus__r),
                            (Select First_Working_Day__c,Last_Working_Day__c from placements__r 
                                Where First_Working_Day__c!=NULL AND Last_Working_Day__c!=NULL
                                Order By First_Working_Day__c)
                         FROM Torc_User__c Where ID in :userId];
        
        list<Referral_Bonus__c>lstrb=new list<Referral_Bonus__c>();
        list<Referral_Bonus__c>lstrbDel=new list<Referral_Bonus__c>();
        for(torc_User__c tu:lsttu)
        {      
            List<Placement__c> lstP = tu.placements__r;
            if(tu.Referral_Bonus__r.size()>0 && (tu.Referral_Bonus__r[0].referral_Payment_Created__c==true || tu.Referral_Bonus__r[0].referrer_Payment_Created__c==true))
                continue;
             date fd=null;
             Date ld=null;
             for(Placement__c p:lstP)
             {
                 fd=fd==null?p.First_Working_Day__c:(fd>p.First_Working_Day__c?p.First_Working_Day__c:fd);
                 ld=ld==null?p.last_Working_Day__c:(ld<p.last_Working_Day__c?p.last_Working_Day__c:ld);
             }
             if(fd!=NULL && ld!=NULL && tu.Referrer__c!=NULL 
                                 && tu.Referrer__r.Exclude_Referrer_Bonus__c !=TRUE
                                 && tu.Exclude_Referral_Bonus__c !=TRUE
               )
             {
                Referral_Bonus__c rb;
                if(tu.Referral_Bonus__r.size()>0)
                    rb = tu.Referral_Bonus__r[0];
                else
                    rb = new Referral_Bonus__c( Referred_to__c = tu.id);
                rb.Referred_By__c = tu.Referrer__c;    
                rb.Payment_Week__c = fd.addmonths(1);
                lstrb.add(rb);
             }
             else
            {
                lstrbDel.addAll(tu.Referral_Bonus__r);
                continue;
            }
        }
        if(lstrbDel.size()>0)
            delete lstrbDel;
        if(lstrb.size()>0)    
            upsert lstrb;    
    }
}