force-app/main/default/objects/Question__c/Question__c.object-meta.xml
<CustomObject>
    <description>A set of Questions to be used when interacting with Talent/Applications at the Validation and Internal Interview Stages for a particular Job Order</description>
    <label>Question</label>
    <nameField>
        <displayFormat>QUE-{0000}</displayFormat>
        <label>Question Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Questions</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Question__c/fields/Category__c.field-meta.xml
<CustomField>
    <fullName>Category__c</fullName>
    <description>Copied from the related Question Template during Job Setup. Categorizes the Question to help explain its relevant Interview style.</description>
    <label>Category</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>General</fullName>
            </value>
            <value>
                <fullName>Job</fullName>
            </value>
            <value>
                <fullName>Behavior</fullName>
            </value>
            <value>
                <fullName>Notes</fullName>
            </value>
            <value>
                <fullName>Transcript</fullName>
            </value>
            <value>
                <fullName>Client Feedback</fullName>
                <isActive>false</isActive>
                <label>Client Feedback</label>
            </value>
            <value>
                <fullName>General Questions</fullName>
                <isActive>false</isActive>
                <label>General Questions</label>
            </value>
            <value>
                <fullName>Intake General Questions</fullName>
                <isActive>false</isActive>
                <label>Intake General Questions</label>
            </value>
            <value>
                <fullName>Interview Details</fullName>
                <isActive>false</isActive>
                <label>Interview Details</label>
            </value>
            <value>
                <fullName>Interviewer (client)</fullName>
                <isActive>false</isActive>
                <label>Interviewer (client)</label>
            </value>
            <value>
                <fullName>Preference</fullName>
                <isActive>false</isActive>
                <label>Preference</label>
            </value>
            <value>
                <fullName>Skill Log</fullName>
                <isActive>false</isActive>
                <label>Skill Log</label>
            </value>
            <value>
                <fullName>Submission Notes</fullName>
                <isActive>false</isActive>
                <label>Submission Notes</label>
            </value>
            <value>
                <fullName>Talent response</fullName>
                <isActive>false</isActive>
                <label>Talent response</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Question__c/fields/Grouping__c.field-meta.xml
<CustomField>
    <fullName>Grouping__c</fullName>
    <description>Copied from the related Question Template during Job Setup. Controls which heading a Question appears underneath when Pre-Screening a Candidate</description>
    <label>Grouping</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>General</fullName>
            </value>
            <value>
                <fullName>Location</fullName>
            </value>
            <value>
                <fullName>Availability</fullName>
            </value>
            <value>
                <fullName>Physical</fullName>
            </value>
            <value>
                <fullName>Experience</fullName>
            </value>
            <value>
                <fullName>Competence</fullName>
            </value>
            <value>
                <fullName>Behavior</fullName>
            </value>
            <value>
                <fullName>Achievements</fullName>
            </value>
            <value>
                <fullName>Client Compliance</fullName>
            </value>
            <value>
                <fullName>Compensation</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Question__c/fields/JobOrder__c.field-meta.xml
<CustomField>
    <fullName>JobOrder__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Job Order</label>
    <referenceTo>TR1__Job__c</referenceTo>
    <relationshipLabel>Questions</relationshipLabel>
    <relationshipName>JobQuestions</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Question__c/fields/KnockOut__c.field-meta.xml
<CustomField>
    <fullName>KnockOut__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Copied from the related Question Template during Job Setup. Controls whether a UI warning appears when a Yes/No Question is responded with &quot;No&quot;</description>
    <label>Knock Out</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Question__c/fields/Order__c.field-meta.xml
<CustomField>
    <fullName>Order__c</fullName>
    <defaultValue>0</defaultValue>
    <description>Provided by the related Question Template during Job Setup. Determines the order of a Question after organizing all Questions by Stage, Category, and then Grouping</description>
    <label>Order</label>
    <precision>5</precision>
    <required>true</required>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Question__c/fields/QuestionTemplate__c.field-meta.xml
<CustomField>
    <fullName>QuestionTemplate__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>The parent Question Template; provides all the Question details defined by Global Core.</description>
    <label>Question Template</label>
    <referenceTo>Question_Template__c</referenceTo>
    <relationshipLabel>Questions</relationshipLabel>
    <relationshipName>JobQuestions</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Question__c/fields/QuestionTextAlt__c.field-meta.xml
<CustomField>
    <fullName>QuestionTextAlt__c</fullName>
    <description>Question in alternate language</description>
    <label>Question Text - Alternate</label>
    <length>1028</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Question__c/fields/QuestionTextEN__c.field-meta.xml
<CustomField>
    <fullName>QuestionTextEN__c</fullName>
    <description>Provided by the related Question Template during Job Setup. Presented during Pre-Screening. Question in English</description>
    <label>Question Text - EN</label>
    <length>1028</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Question__c/fields/Stage__c.field-meta.xml
<CustomField>
    <fullName>Stage__c</fullName>
    <description>Copied from the related Question Template during Job Setup. Controls whether the question should appear during the Validation or Internal Interview Stage (eg. ATS modal).</description>
    <label>Stage</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Internal Interview</fullName>
            </value>
            <value>
                <fullName>Application</fullName>
            </value>
            <value>
                <fullName>Client Interview</fullName>
            </value>
            <value>
                <fullName>Closing Report</fullName>
                <isActive>false</isActive>
                <label>Closing Report</label>
            </value>
            <value>
                <fullName>Intake</fullName>
                <isActive>false</isActive>
                <label>Intake</label>
            </value>
            <value>
                <fullName>Offer</fullName>
                <isActive>false</isActive>
                <label>Offer</label>
            </value>
            <value>
                <fullName>Proposed to Client</fullName>
                <isActive>false</isActive>
                <label>Proposed to Client</label>
            </value>
            <value>
                <fullName>Send Out</fullName>
                <isActive>false</isActive>
                <label>Send Out</label>
            </value>
            <value>
                <fullName>Submittal</fullName>
                <isActive>false</isActive>
                <label>Submittal</label>
            </value>
            <value>
                <fullName>Testing</fullName>
                <isActive>false</isActive>
                <label>Testing</label>
            </value>
            <value>
                <fullName>Validation</fullName>
                <isActive>false</isActive>
                <label>Validation</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Question_Template__c/Question_Template__c.object-meta.xml
<CustomObject>
    <label>Question Template</label>
    <nameField>
        <displayFormat>QES-{000000}</displayFormat>
        <label>Question_ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Questions_Template</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Question_Template__c/fields/AnswerOptions__c.field-meta.xml
<CustomField>
    <fullName>AnswerOptions__c</fullName>
    <description>Comma-delimited list of possible, mutually-exclusive options. An Interface interprets this to render a choice for the user (such as a picklist, radio button, menu)</description>
    <inlineHelpText>Enter possible values separated by a comma. Eg. &quot;immediately,two week notice,one month notice,more than one month notice&quot;</inlineHelpText>
    <label>Answer Options</label>
    <type>TextArea</type>
</CustomField>

force-app/main/default/objects/Question_Template__c/fields/AnswerType__c.field-meta.xml
<CustomField>
    <fullName>AnswerType__c</fullName>
    <description>Informs the Interface on how to present a question to a User as well as enables Knock Out functionality (Yes/No) or possible Answer options (Picklist)</description>
    <inlineHelpText>Describe how the Applicant should Answer the Question</inlineHelpText>
    <label>Answer Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Date</fullName>
            </value>
            <value>
                <fullName>Picklist</fullName>
            </value>
            <value>
                <fullName>Text</fullName>
            </value>
            <value>
                <fullName>Boolean</fullName>
                <label>Yes/No</label>
            </value>
            <value>
                <fullName>Paragraph</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Question_Template__c/fields/Category__c.field-meta.xml
<CustomField>
    <fullName>Category__c</fullName>
    <description>Categorizes the Question to help explain its relevant Interview style.</description>
    <inlineHelpText>Categorizes the Question to help explain its relevant Interview style</inlineHelpText>
    <label>Category</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>General</fullName>
            </value>
            <value>
                <fullName>Job</fullName>
            </value>
            <value>
                <fullName>Behavior</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Question_Template__c/fields/Grouping__c.field-meta.xml
<CustomField>
    <fullName>Grouping__c</fullName>
    <description>Controls which heading a Question appears underneath when Pre-Screening a Candidate</description>
    <inlineHelpText>Choose which Heading this Question should appear under during Pre-Screening</inlineHelpText>
    <label>Grouping</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>General</fullName>
            </value>
            <value>
                <fullName>Location</fullName>
            </value>
            <value>
                <fullName>Availability</fullName>
            </value>
            <value>
                <fullName>Compensation</fullName>
            </value>
            <value>
                <fullName>Physical</fullName>
            </value>
            <value>
                <fullName>Experience</fullName>
            </value>
            <value>
                <fullName>Achievements</fullName>
            </value>
            <value>
                <fullName>Client Compliance</fullName>
            </value>
            <value>
                <fullName>Behavior</fullName>
            </value>
            <value>
                <fullName>Competence</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Question_Template__c/fields/KnockOut__c.field-meta.xml
<CustomField>
    <fullName>KnockOut__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Controls whether a UI warning appears when a boolean Question is answered No/False</description>
    <inlineHelpText>A warning will appear if the Answer is &quot;No&quot;</inlineHelpText>
    <label>Knock Out</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Question_Template__c/fields/Mandatory__c.field-meta.xml
<CustomField>
    <fullName>Mandatory__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Controls whether a Question is required to be displayed and answered at the Prescreening Stage. Mandatory questions may not be deselected by a user during Job Setup. Pre-set by the global core</description>
    <inlineHelpText>When checked, this Question is required to be displayed and answered at the Prescreening Stage.</inlineHelpText>
    <label>Mandatory</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Question_Template__c/fields/Order__c.field-meta.xml
<CustomField>
    <fullName>Order__c</fullName>
    <defaultValue>0</defaultValue>
    <description>Determines the order of a Question after organizing all Questions by Stage, Category, and then Grouping</description>
    <inlineHelpText>A higher value will be at the top of a list of Questions</inlineHelpText>
    <label>Order</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Question_Template__c/fields/QuestionTextAlt__c.field-meta.xml
<CustomField>
    <fullName>QuestionTextAlt__c</fullName>
    <description>Question in alternate language</description>
    <label>Question Text - Alternate</label>
    <length>1028</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Question_Template__c/fields/QuestionTextEN__c.field-meta.xml
<CustomField>
    <fullName>QuestionTextEN__c</fullName>
    <description>Presented during Pre-Screening. FUTURE STATE: made available to RCE.Question in English</description>
    <label>Question Text - EN</label>
    <length>1028</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/classes/QuestionTemplateController.cls
public with sharing class QuestionTemplateController {
    @AuraEnabled(cacheable=true)
    public static Map<String, List<Question_Template__c>> getQuestionsGroupedByGrouping(Id jobOrderId) {
        Map<String, List<Question_Template__c>> groupedQuestions = new Map<String, List<Question_Template__c>>();

        // Query the selected questions
        Set<Id> selectedQuestionIds = new Set<Id>();
        for (Question__c question : [SELECT QuestionTemplate__c FROM Question__c WHERE JobOrder__c = :jobOrderId]) {
            selectedQuestionIds.add(question.QuestionTemplate__c);
        }
        system.debug('selectedQuestionIds'+selectedQuestionIds);

        // Query the Question Templates
        for (Question_Template__c qt : [SELECT Id, AnswerOptions__c, AnswerType__c, Category__c, Grouping__c, KnockOut__c, Mandatory__c, QuestionTextAlt__c, QuestionTextEN__c, Stage__c,Order__c FROM Question_Template__c WHERE Stage__c = 'Application' WITH SECURITY_ENFORCED]) {
            if (!groupedQuestions.containsKey(qt.Grouping__c)) {
                groupedQuestions.put(qt.Grouping__c, new List<Question_Template__c>());
            }

            groupedQuestions.get(qt.Grouping__c).add(qt);
        }
        system.debug('groupedQuestions'+groupedQuestions);
        return groupedQuestions;
    }

    @AuraEnabled(cacheable=true)
    public static Boolean checkSetupCompleted(Id jobOrderId) {
        Integer questionCount = [SELECT COUNT() FROM Question__c WHERE JobOrder__c = :jobOrderId];
        return questionCount > 0;
    }

    @AuraEnabled
    public static void saveSelectedQuestions(List<Question_Template__c> selectedQuestions, Id jobOrderId) {
        List<Question__c> questionsToInsert = new List<Question__c>();
        system.debug('selectedQuestions'+selectedQuestions);
        for (Question_Template__c selectedQuestion : selectedQuestions) {
            Question__c question = new Question__c();
            question.JobOrder__c = jobOrderId;
            question.QuestionTemplate__c = selectedQuestion.Id;
            question.QuestionTextEN__c = selectedQuestion.QuestionTextEN__c;
            question.QuestionTextAlt__c = selectedQuestion.QuestionTextAlt__c;
            question.Category__c = selectedQuestion.Category__c;
            question.Grouping__c = selectedQuestion.Grouping__c;
            question.KnockOut__c = selectedQuestion.KnockOut__c;
            question.MandatoryToBeAsked__c = selectedQuestion.Mandatory__c;
            question.Order__c = selectedQuestion.Order__c;
            question.ResponseOptions__c = selectedQuestion.AnswerOptions__c;
            question.ResponseType__c = selectedQuestion.AnswerType__c;
            question.Stage__c = selectedQuestion.Stage__c;
            question.VariableSource__c = selectedQuestion.VariableSource__c;

            questionsToInsert.add(question);
        }

        if (!questionsToInsert.isEmpty()) {
            insert questionsToInsert;
        }
    }
}