force-app/main/default/objects/Question__c/Question__c.object-meta.xml
<CustomObject>
    <description>A set of Questions to be used when interacting with Talent/Applications at the Validation and Internal Interview Stages for a particular Job Order</description>
    <label>Question</label>
    <nameField>
        <displayFormat>QUE-{0000}</displayFormat>
        <label>Question Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Questions</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Question__c/fields/Category__c.field-meta.xml
<CustomField>
    <fullName>Category__c</fullName>
    <description>Copied from the related Question Template during Job Setup. Categorizes the Question to help explain its relevant Interview style.</description>
    <label>Category</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>General</fullName>
            </value>
            <value>
                <fullName>Job</fullName>
            </value>
            <value>
                <fullName>Behavior</fullName>
            </value>
            <value>
                <fullName>Notes</fullName>
            </value>
            <value>
                <fullName>Transcript</fullName>
            </value>
            <value>
                <fullName>Client Feedback</fullName>
                <isActive>false</isActive>
                <label>Client Feedback</label>
            </value>
            <value>
                <fullName>General Questions</fullName>
                <isActive>false</isActive>
                <label>General Questions</label>
            </value>
            <value>
                <fullName>Intake General Questions</fullName>
                <isActive>false</isActive>
                <label>Intake General Questions</label>
            </value>
            <value>
                <fullName>Interview Details</fullName>
                <isActive>false</isActive>
                <label>Interview Details</label>
            </value>
            <value>
                <fullName>Interviewer (client)</fullName>
                <isActive>false</isActive>
                <label>Interviewer (client)</label>
            </value>
            <value>
                <fullName>Preference</fullName>
                <isActive>false</isActive>
                <label>Preference</label>
            </value>
            <value>
                <fullName>Skill Log</fullName>
                <isActive>false</isActive>
                <label>Skill Log</label>
            </value>
            <value>
                <fullName>Submission Notes</fullName>
                <isActive>false</isActive>
                <label>Submission Notes</label>
            </value>
            <value>
                <fullName>Talent response</fullName>
                <isActive>false</isActive>
                <label>Talent response</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Question__c/fields/Grouping__c.field-meta.xml
<CustomField>
    <fullName>Grouping__c</fullName>
    <description>Copied from the related Question Template during Job Setup. Controls which heading a Question appears underneath when Pre-Screening a Candidate</description>
    <label>Grouping</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>General</fullName>
            </value>
            <value>
                <fullName>Location</fullName>
            </value>
            <value>
                <fullName>Availability</fullName>
            </value>
            <value>
                <fullName>Physical</fullName>
            </value>
            <value>
                <fullName>Experience</fullName>
            </value>
            <value>
                <fullName>Competence</fullName>
            </value>
            <value>
                <fullName>Behavior</fullName>
            </value>
            <value>
                <fullName>Achievements</fullName>
            </value>
            <value>
                <fullName>Client Compliance</fullName>
            </value>
            <value>
                <fullName>Compensation</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Question__c/fields/KnockOut__c.field-meta.xml
<CustomField>
    <fullName>KnockOut__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Copied from the related Question Template during Job Setup. Controls whether a UI warning appears when a Yes/No Question is responded with &quot;No&quot;</description>
    <label>Knock Out</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Question__c/fields/Order__c.field-meta.xml
<CustomField>
    <fullName>Order__c</fullName>
    <defaultValue>0</defaultValue>
    <description>Provided by the related Question Template during Job Setup. Determines the order of a Question after organizing all Questions by Stage, Category, and then Grouping</description>
    <label>Order</label>
    <precision>5</precision>
    <required>true</required>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Question__c/fields/QuestionTextAlt__c.field-meta.xml
<CustomField>
    <fullName>QuestionTextAlt__c</fullName>
    <description>Question in alternate language</description>
    <label>Question Text - Alternate</label>
    <length>1028</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Question__c/fields/QuestionTextEN__c.field-meta.xml
<CustomField>
    <fullName>QuestionTextEN__c</fullName>
    <description>Provided by the related Question Template during Job Setup. Presented during Pre-Screening. Question in English</description>
    <label>Question Text - EN</label>
    <length>1028</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Question__c/fields/Stage__c.field-meta.xml
<CustomField>
    <fullName>Stage__c</fullName>
    <description>Copied from the related Question Template during Job Setup. Controls whether the question should appear during the Validation or Internal Interview Stage (eg. ATS modal).</description>
    <label>Stage</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Internal Interview</fullName>
            </value>
            <value>
                <fullName>Application</fullName>
            </value>
            <value>
                <fullName>Client Interview</fullName>
            </value>
            <value>
                <fullName>Closing Report</fullName>
                <isActive>false</isActive>
                <label>Closing Report</label>
            </value>
            <value>
                <fullName>Intake</fullName>
                <isActive>false</isActive>
                <label>Intake</label>
            </value>
            <value>
                <fullName>Offer</fullName>
                <isActive>false</isActive>
                <label>Offer</label>
            </value>
            <value>
                <fullName>Proposed to Client</fullName>
                <isActive>false</isActive>
                <label>Proposed to Client</label>
            </value>
            <value>
                <fullName>Send Out</fullName>
                <isActive>false</isActive>
                <label>Send Out</label>
            </value>
            <value>
                <fullName>Submittal</fullName>
                <isActive>false</isActive>
                <label>Submittal</label>
            </value>
            <value>
                <fullName>Testing</fullName>
                <isActive>false</isActive>
                <label>Testing</label>
            </value>
            <value>
                <fullName>Validation</fullName>
                <isActive>false</isActive>
                <label>Validation</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Question_Template__c/Question_Template__c.object-meta.xml
<CustomObject>
    <label>Question Template</label>
    <nameField>
        <displayFormat>QES-{000000}</displayFormat>
        <label>Question_ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Questions_Template</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Question_Template__c/fields/AnswerOptions__c.field-meta.xml
<CustomField>
    <fullName>AnswerOptions__c</fullName>
    <description>Comma-delimited list of possible, mutually-exclusive options. An Interface interprets this to render a choice for the user (such as a picklist, radio button, menu)</description>
    <inlineHelpText>Enter possible values separated by a comma. Eg. &quot;immediately,two week notice,one month notice,more than one month notice&quot;</inlineHelpText>
    <label>Answer Options</label>
    <type>TextArea</type>
</CustomField>

force-app/main/default/objects/Question_Template__c/fields/AnswerType__c.field-meta.xml
<CustomField>
    <fullName>AnswerType__c</fullName>
    <description>Informs the Interface on how to present a question to a User as well as enables Knock Out functionality (Yes/No) or possible Answer options (Picklist)</description>
    <inlineHelpText>Describe how the Applicant should Answer the Question</inlineHelpText>
    <label>Answer Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Date</fullName>
            </value>
            <value>
                <fullName>Picklist</fullName>
            </value>
            <value>
                <fullName>Text</fullName>
            </value>
            <value>
                <fullName>Boolean</fullName>
                <label>Yes/No</label>
            </value>
            <value>
                <fullName>Paragraph</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Question_Template__c/fields/Category__c.field-meta.xml
<CustomField>
    <fullName>Category__c</fullName>
    <description>Categorizes the Question to help explain its relevant Interview style.</description>
    <inlineHelpText>Categorizes the Question to help explain its relevant Interview style</inlineHelpText>
    <label>Category</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>General</fullName>
            </value>
            <value>
                <fullName>Job</fullName>
            </value>
            <value>
                <fullName>Behavior</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Question_Template__c/fields/Grouping__c.field-meta.xml
<CustomField>
    <fullName>Grouping__c</fullName>
    <description>Controls which heading a Question appears underneath when Pre-Screening a Candidate</description>
    <inlineHelpText>Choose which Heading this Question should appear under during Pre-Screening</inlineHelpText>
    <label>Grouping</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>General</fullName>
            </value>
            <value>
                <fullName>Location</fullName>
            </value>
            <value>
                <fullName>Availability</fullName>
            </value>
            <value>
                <fullName>Compensation</fullName>
            </value>
            <value>
                <fullName>Physical</fullName>
            </value>
            <value>
                <fullName>Experience</fullName>
            </value>
            <value>
                <fullName>Achievements</fullName>
            </value>
            <value>
                <fullName>Client Compliance</fullName>
            </value>
            <value>
                <fullName>Behavior</fullName>
            </value>
            <value>
                <fullName>Competence</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Question_Template__c/fields/KnockOut__c.field-meta.xml
<CustomField>
    <fullName>KnockOut__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Controls whether a UI warning appears when a boolean Question is answered No/False</description>
    <inlineHelpText>A warning will appear if the Answer is &quot;No&quot;</inlineHelpText>
    <label>Knock Out</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Question_Template__c/fields/Mandatory__c.field-meta.xml
<CustomField>
    <fullName>Mandatory__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Controls whether a Question is required to be displayed and answered at the Prescreening Stage. Mandatory questions may not be deselected by a user during Job Setup. Pre-set by the global core</description>
    <inlineHelpText>When checked, this Question is required to be displayed and answered at the Prescreening Stage.</inlineHelpText>
    <label>Mandatory</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Question_Template__c/fields/Order__c.field-meta.xml
<CustomField>
    <fullName>Order__c</fullName>
    <defaultValue>0</defaultValue>
    <description>Determines the order of a Question after organizing all Questions by Stage, Category, and then Grouping</description>
    <inlineHelpText>A higher value will be at the top of a list of Questions</inlineHelpText>
    <label>Order</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Question_Template__c/fields/QuestionTextAlt__c.field-meta.xml
<CustomField>
    <fullName>QuestionTextAlt__c</fullName>
    <description>Question in alternate language</description>
    <label>Question Text - Alternate</label>
    <length>1028</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Question_Template__c/fields/QuestionTextEN__c.field-meta.xml
<CustomField>
    <fullName>QuestionTextEN__c</fullName>
    <description>Presented during Pre-Screening. FUTURE STATE: made available to RCE.Question in English</description>
    <label>Question Text - EN</label>
    <length>1028</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Question_Template__c/fields/Stage__c.field-meta.xml
<CustomField>
    <fullName>Stage__c</fullName>
    <description>Controls whether the question should appear during the Validation or Internal Interview Stage (eg. ATS modal)</description>
    <inlineHelpText>Choose which part of the Candidate process this question is relevant to</inlineHelpText>
    <label>Stage</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Internal Interview</fullName>
            </value>
            <value>
                <fullName>Application</fullName>
            </value>
            <value>
                <fullName>Validation</fullName>
                <isActive>false</isActive>
                <label>Validation</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/QuestionTemplateControllerTest.cls
@IsTest
public class QuestionTemplateControllerTest {
    @IsTest
    static void testGetQuestionsGroupedByGrouping() {
        // Setup test data
        TR1__Job__c jobOrder = new TR1__Job__c(Name = 'Test Job Order', Job_Type__c='contract');
        insert jobOrder;

        Question_Template__c qt1 = new Question_Template__c(
            AnswerOptions__c = 'Option1;Option2',
            AnswerType__c = 'Picklist',
            Category__c = 'General',
            Grouping__c = 'General',
            KnockOut__c = false,
            Mandatory__c = false,
            QuestionTextAlt__c = 'Are you are at least 18 years of age?',
            QuestionTextEN__c = 'Are you are at least 18 years of age?',
            Stage__c = 'Application',
            Order__c = 1
        );
        Question_Template__c qt2 = new Question_Template__c(
            AnswerOptions__c = 'Option3;Option4',
            AnswerType__c = 'Picklist',
            Category__c = 'Job',
            Grouping__c = 'Availability',
            KnockOut__c = false,
            Mandatory__c = false,
            QuestionTextAlt__c = 'How much notice time would you need before starting a new job?',
            QuestionTextEN__c = 'How much notice time would you need before starting a new job?',
            Stage__c = 'Application',
            Order__c = 2
        );
        insert new List<Question_Template__c> { qt1, qt2 };

        Question__c question = new Question__c(
            JobOrder__c = jobOrder.Id,
            QuestionTemplate__c = qt1.Id,
            Grouping__c='General',
            Stage__c='Application'
        );
        insert question;

        // Test the method
        Test.startTest();
        Map<String, List<Question_Template__c>> result = QuestionTemplateController.getQuestionsGroupedByGrouping(jobOrder.Id);
        Test.stopTest();
        
        system.debug('result'+result);

        // Verify results

        //System.assert(result.containsKey('Availability'), 'Availability');
       // System.assert(result.containsKey('General'), 'General');
        //System.assertEquals(1, result.get('Grouping__c').size(), 1);
     
    }

   @IsTest
    static void testCheckSetupCompleted() {
        // Setup test data
        TR1__Job__c jobOrder = new TR1__Job__c(Name = 'Test Job Order',Job_Type__c='contract');
        insert jobOrder;

        Question__c question = new Question__c(
            JobOrder__c = jobOrder.Id,
            QuestionTemplate__c = null,
            Grouping__c='General',
            Stage__c='Application'
        );
        insert question;

        // Test the method
        Test.startTest();
        Boolean isSetupCompleted = QuestionTemplateController.checkSetupCompleted(jobOrder.Id);
        Test.stopTest();

        // Verify results
        System.assert(isSetupCompleted, 'Setup should be completed because there is one question');
    }

    @IsTest
    static void testSaveSelectedQuestions() {
        // Setup test data
        TR1__Job__c jobOrder = new TR1__Job__c(Name = 'Test Job Order',Job_Type__c='contract');
        insert jobOrder;

        Question_Template__c qt1 = new Question_Template__c(
            AnswerOptions__c = 'Option1;Option2',
            AnswerType__c = 'Picklist',
            Category__c = 'General',
            Grouping__c = 'General',
            KnockOut__c = false,
            Mandatory__c = false,
            QuestionTextAlt__c = 'Are you are at least 18 years of age?',
            QuestionTextEN__c = 'Are you are at least 18 years of age?',
            Stage__c = 'Application',
            Order__c = 1
        );
        insert qt1;

        // Test the method
        Test.startTest();
        QuestionTemplateController.saveSelectedQuestions(new List<Question_Template__c> { qt1 }, jobOrder.Id);
        Test.stopTest();

        // Verify results
        List<Question__c> insertedQuestions = [SELECT Id, QuestionTemplate__c FROM Question__c WHERE JobOrder__c = :jobOrder.Id];
        System.assertEquals(1, insertedQuestions.size(), 'One question should have been inserted');
        System.assertEquals(qt1.Id, insertedQuestions[0].QuestionTemplate__c, 'The question should reference the correct template');
    }
}