force-app/main/default/objects/RD_ChangeEvent__e/RD_ChangeEvent__e.object-meta.xml
<CustomObject>
    <description>Platform Event to capture record Ids that have been inserted updated</description>
    <label>RD Change Event</label>
    <pluralLabel>RD Change Events</pluralLabel>
</CustomObject>

force-app/main/default/objects/RD_ChangeEvent__e/fields/Changed_By__c.field-meta.xml
<CustomField>
    <fullName>Changed_By__c</fullName>
    <label>Changed By</label>
    <length>80</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/RD_ChangeEvent__e/fields/Fields__c.field-meta.xml
<CustomField>
    <fullName>Fields__c</fullName>
    <label>Fields</label>
    <length>131072</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/RD_ChangeEvent__e/fields/Record_Id__c.field-meta.xml
<CustomField>
    <fullName>Record_Id__c</fullName>
    <label>Record ID</label>
    <length>18</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/RD_ChangeEvent__e/fields/Source__c.field-meta.xml
<CustomField>
    <fullName>Source__c</fullName>
    <label>Source</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/RD_ChangeEvent_Test.cls
@IsTest
private class RD_ChangeEvent_Test {

    @isTest
    private static void test_RDChangeEvent() {
        RD_ChangeEvent__e evt = new RD_ChangeEvent__e();
        evt.Change_Type__c = 'Insert';
        evt.Changed_By__c = 'ABC';
        evt.Entity__c = 'Account';
        evt.Fields__c = '{"A":"B"}';
        evt.Record_Id__c = 'AAAA';
        evt.Source__c = 'User';
        evt.Timestamp__c = System.now();
        
        Test.startTest();
            Database.SaveResult result = EventBus.publish(evt);
        Test.stopTest();
    }

}