force-app/main/default/objects/Trolley_Batch__c/Trolley_Batch__c.object-meta.xml
<CustomObject>
    <label>Trolley Batch</label>
    <nameField>
        <displayFormat>batch-{000000}</displayFormat>
        <label>Trolley Batch Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Trolley Batchs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Trolley_Invoice__c/Trolley_Invoice__c.object-meta.xml
<CustomObject>
    <label>Trolley Invoice</label>
    <nameField>
        <displayFormat>{0000000}</displayFormat>
        <label>Trolley Invoice Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Trolley Invoices</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Trolley_Invoice__c/fields/Pass_Number__c.field-meta.xml
<CustomField>
    <fullName>Pass_Number__c</fullName>
    <label>Pass Number</label>
    <precision>3</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Trolley_Invoice__c/fields/Trolley_Batch__c.field-meta.xml
<CustomField>
    <fullName>Trolley_Batch__c</fullName>
    <label>Trolley Batch</label>
    <referenceTo>Trolley_Batch__c</referenceTo>
    <relationshipLabel>Trolley Invoices</relationshipLabel>
    <relationshipName>Trolley_Invoices</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/classes/trolleyAPICallScheduler.cls
global class trolleyAPICallScheduler implements Schedulable 
{
    public id batchId= null;
    public integer passNumber = -1;   
    global void execute(SchedulableContext SC) 
    {
        system.debug('SCHEDULE EXECUTION '+passNumber);
        TrolleyAPICallBatch myBatchObject = new TrolleyAPICallBatch(batchId,passNumber); 
        Database.executeBatch(myBatchObject,1);
        for(Trolley_Invoice__c a:[Select ID from Trolley_Invoice__c  WHERE Trolley_Batch__c=:batchId and Pass_Number__c = :(passNumber+1) LIMIT 1])
        {
            system.debug('Calling Next batch '+ (passNumber+1));
            System.enqueueJob(new TrolleyAPICallQueue(batchid,passNumber+1));
        }
    }
    
}