force-app/main/default/objects/Trolley_Batch__c/Trolley_Batch__c.object-meta.xml
<CustomObject>
    <label>Trolley Batch</label>
    <nameField>
        <displayFormat>batch-{000000}</displayFormat>
        <label>Trolley Batch Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Trolley Batchs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Trolley_Batch__c/fields/Trolley_Id__c.field-meta.xml
<CustomField>
    <fullName>Trolley_Id__c</fullName>
    <label>Trolley Id</label>
    <length>30</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Trolley_Invoice__c/Trolley_Invoice__c.object-meta.xml
<CustomObject>
    <label>Trolley Invoice</label>
    <nameField>
        <displayFormat>{0000000}</displayFormat>
        <label>Trolley Invoice Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Trolley Invoices</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Trolley_Invoice__c/fields/Cover_Fee__c.field-meta.xml
<CustomField>
    <fullName>Cover_Fee__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Cover Fee</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Trolley_Invoice__c/fields/Memo__c.field-meta.xml
<CustomField>
    <fullName>Memo__c</fullName>
    <label>Memo</label>
    <length>2000</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Trolley_Invoice__c/fields/Trolley_Batch__c.field-meta.xml
<CustomField>
    <fullName>Trolley_Batch__c</fullName>
    <label>Trolley Batch</label>
    <referenceTo>Trolley_Batch__c</referenceTo>
    <relationshipLabel>Trolley Invoices</relationshipLabel>
    <relationshipName>Trolley_Invoices</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Trolley_Invoice__c/fields/Trolley_Id__c.field-meta.xml
<CustomField>
    <fullName>Trolley_Id__c</fullName>
    <label>Trolley Id</label>
    <length>30</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Trolley_Invoice__c/fields/trolley_Invoicing_Payment_Id__c.field-meta.xml
<CustomField>
    <fullName>trolley_Invoicing_Payment_Id__c</fullName>
    <label>Trolley Invoicing Payment Id</label>
    <length>30</length>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/trolleyInvoiceUpdate.cls
Public class trolleyInvoiceUpdate
{
    public Trolley_Invoice__c tInv{get;set;}
    public trolleyInvoiceUpdate(ApexPages.StandardController controller)
    {
        tInv = (Trolley_Invoice__c) controller.getRecord();
        tInv = [Select id, Memo__c, Cover_Fee__c, 
                                    trolley_Invoicing_Payment_Id__c, 
                                    Trolley_batch__c,Trolley_batch__r.Trolley_Id__c
                                FROM Trolley_Invoice__c  where id=:tInv.Id];
    }
    public pagereference toggleCoverFee()
    {
        tInv.Cover_Fee__c= !tInv.Cover_Fee__c;
        TrolleyAPICallBatch.updatePayment(tInv);
        update tInv;
        return new Pagereference('/'+tInv.Trolley_Batch__c);
    }
}