force-app/main/default/objects/Torc_User__c/Torc_User__c.object-meta.xml
<CustomObject>
    <label>Torc User</label>
    <nameField>
        <label>Torc User Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Torc Users</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Torc_User__c/fields/External_ID__c.field-meta.xml
<CustomField>
    <fullName>External_ID__c</fullName>
    <externalId>true</externalId>
    <label>External ID</label>
    <length>50</length>
    <required>true</required>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/classes/torcUserRedirect.cls
public class torcUserRedirect
{
    public Pagereference redirect()
    {
        for(Torc_User__c tu:[Select ID from Torc_User__c where External_Id__c = :id])
            return new Pagereference('/'+tu.id);
        error = 'Invalid Id';    
        return null; 
    }
    public string id{get;set;}
    public string error{get;set;}
    public torcUserRedirect()
    {
        error = 'Redirecting........';
        id= ApexPages.currentPage().getParameters().get('id');
        
    }
}