force-app/main/default/objects/Audit_Trail__c/Audit_Trail__c.object-meta.xml
<CustomObject>
    <label>Audit Trail</label>
    <nameField>
        <displayFormat>AT-{000000}</displayFormat>
        <label>Audit Trail Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Audit Trails</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Audit_Trail__c/fields/Action__c.field-meta.xml
<CustomField>
    <fullName>Action__c</fullName>
    <label>Action</label>
    <length>30</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Audit_Trail__c/fields/Audit_ID__c.field-meta.xml
<CustomField>
    <fullName>Audit_ID__c</fullName>
    <externalId>true</externalId>
    <label>Audit ID</label>
    <length>18</length>
    <required>true</required>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/Audit_Trail__c/fields/Developer__c.field-meta.xml
<CustomField>
    <fullName>Developer__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Developer</label>
    <referenceTo>User</referenceTo>
    <relationshipName>Audit_Trails</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Audit_Trail__c/fields/Handled__c.field-meta.xml
<CustomField>
    <fullName>Handled__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Handled</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Audit_Trail__c/fields/Operation__c.field-meta.xml
<CustomField>
    <fullName>Operation__c</fullName>
    <label>Operation</label>
    <type>TextArea</type>
</CustomField>

force-app/main/default/objects/Audit_Trail__c/fields/Performed_On__c.field-meta.xml
<CustomField>
    <fullName>Performed_On__c</fullName>
    <label>Performed On</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/Audit_Trail__c/fields/Section__c.field-meta.xml
<CustomField>
    <fullName>Section__c</fullName>
    <label>Section</label>
    <length>80</length>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/auditTrailRecording.cls
global class auditTrailRecording implements Schedulable 
{
    global void execute(SchedulableContext SC) 
    {
        DateTime dt = DateTime.Now().adddays(-45);
        for(Audit_Trail__c rec:[Select Id, Performed_On__c from Audit_Trail__c Order by Performed_On__c DESC LIMIT 1])
        {
            system.debug(rec.Performed_On__c);
            dt=rec.Performed_On__c.addhours(-1);
        }    
        system.debug(dt);   
        integer maxLimit = 4000;
        
        if (Test.isRunningTest()) {
            maxLimit = 5;
        }
         
        for(List<SetupAuditTrail> lst:[SELECT Id, Action, CreatedById, CreatedDate, Display, Section 
                                            FROM SetupAuditTrail 
                                            WHERE Action in 
                                            (   'deletedCF','changedCFType','createdCF',
                                                'deletedCFCustom','changedCFTypeCustom','createdCFCustom',
                                                'createdCFLookup','changedCFLookup','deletedCFLookup',
                                                'createdCFLookupCustom','changedCFLookupCustom','deletedCFLookupCustom',
                                                'changedCFDefaultFormula', 'createdCFFormula', 'deletedCFDefaultFormula', 
                                                'changedCFFormulaCustom', 'createdCFFormulaCustom', 
                                                'deletedCFFormulaCustom' ,'changedCFFormula'
                                            )
                                            AND CreatedDate>=:dt
                                            Order by CreatedDate
                                            LIMIT :maxLimit])
        {
            List< Audit_Trail__c> lstnew=new List< Audit_Trail__c>();
            for(SetupAuditTrail rec:lst)
            {
                Audit_Trail__c recNew=new Audit_Trail__c(Audit_ID__c = rec.id, 
                                                      Action__c = rec.Action, 
                                                      Developer__c = rec.CreatedbyId,
                                                      Handled__c = false,
                                                      Operation__c = (rec.Display==NULL?NULL:rec.Display.left(255)),
                                                      Performed_On__c = rec.CreatedDate,
                                                      Section__c = rec.Section);
                 lstnew.add(recNew);  
            } 
            upsert lstnew  Audit_ID__c;                                                     
        }                                                        
    }
}