force-app/main/default/objects/Log_API__e/Log_API__e.object-meta.xml
<CustomObject>
    <label>Log API</label>
    <pluralLabel>Log API</pluralLabel>
</CustomObject>

force-app/main/default/objects/Log_API__e/fields/Input_Log__c.field-meta.xml
<CustomField>
    <fullName>Input_Log__c</fullName>
    <label>Input Log</label>
    <length>2002</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Log_API__e/fields/Log__c.field-meta.xml
<CustomField>
    <fullName>Log__c</fullName>
    <label>Log</label>
    <length>2002</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Log_API__e/fields/Parent__c.field-meta.xml
<CustomField>
    <fullName>Parent__c</fullName>
    <label>Parent</label>
    <length>40</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Log_API__e/fields/Type__c.field-meta.xml
<CustomField>
    <fullName>Type__c</fullName>
    <label>Type</label>
    <length>40</length>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/LogAPI.cls
Public class LogAPI
{
    public static void publishEvent(string type, string parent, string log)
    {
        publishEvent(type, parent, log,'');
    }
    public static void publishEvent(string type, string parent, string log,string inputLog)
    {
        Log_Api__e l = new Log_Api__e(Type__c=type,Parent__c=parent);
        l.log__c=log==NULL?'':log.left(2000);
        l.Input_Log__c=inputLog==NULL?'':inputLog.left(2000);
        EventBus.publish(l);
    }
}