force-app/main/default/objects/Dummy_Object__c/Dummy_Object__c.object-meta.xml
<CustomObject>
    <description>Temporary object used for display in VF pages</description>
    <label>Dummy Object</label>
    <nameField>
        <displayFormat>D-{00}</displayFormat>
        <label>Dummy Object Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Dummy Object</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Dummy_Object__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Dummy Object</relationshipLabel>
    <relationshipName>Dummy_Object</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Non_Torc_Payment__c/Non_Torc_Payment__c.object-meta.xml
<CustomObject>
    <label>Non Torc Payment</label>
    <nameField>
        <label>Payment Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Non Torc Payments</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Non_Torc_Payment__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Non Torc Payments</relationshipLabel>
    <relationshipName>Non_Torc_Payments</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Non_Torc_Payment__c/fields/For_Month__c.field-meta.xml
<CustomField>
    <fullName>For_Month__c</fullName>
    <label>For Month</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Non_Torc_Payment__c/fields/Friendly_Name__c.field-meta.xml
<CustomField>
    <fullName>Friendly_Name__c</fullName>
    <formula>Non_Torc_User__r.Given_Name__c +&apos; &apos;+ Non_Torc_User__r.Family_Name__c+&apos; &apos;+
TEXT(MONTH( For_Month__c))+&apos;/&apos;+ TEXT(YEAR(For_Month__c))</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Friendly Name</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Non_Torc_Payment__c/fields/Non_Torc_User__c.field-meta.xml
<CustomField>
    <fullName>Non_Torc_User__c</fullName>
    <label>Non Torc User</label>
    <referenceTo>Non_Torc_User__c</referenceTo>
    <relationshipLabel>Non Torc Payments</relationshipLabel>
    <relationshipName>Non_Torc_Payments</relationshipName>
    <relationshipOrder>1</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Non_Torc_Payment__c/fields/Payment_Created__c.field-meta.xml
<CustomField>
    <fullName>Payment_Created__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Payment Created</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Non_Torc_Payment__c/fields/Talent_UserName__c.field-meta.xml
<CustomField>
    <fullName>Talent_UserName__c</fullName>
    <formula>Non_Torc_User__r.Official_Email__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Talent UserName</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Non_Torc_Payment__c/fields/Total_Amount__c.field-meta.xml
<CustomField>
    <fullName>Total_Amount__c</fullName>
    <label>Total Amount</label>
    <precision>12</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Non_Torc_User__c/Non_Torc_User__c.object-meta.xml
<CustomObject>
    <label>Non Torc User</label>
    <nameField>
        <label>Non Torc User Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Non Torc Users</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Non_Torc_User__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Non Torc Users</relationshipLabel>
    <relationshipName>Non_Torc_Users</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Non_Torc_User__c/fields/Custom_Memo_On_Payment__c.field-meta.xml
<CustomField>
    <fullName>Custom_Memo_On_Payment__c</fullName>
    <label>Custom Memo On Payment</label>
    <type>TextArea</type>
</CustomField>

force-app/main/default/objects/Non_Torc_User__c/fields/External_Id__c.field-meta.xml
<CustomField>
    <fullName>External_Id__c</fullName>
    <formula>IF(Official_Email__c=NULL,Email__c,Official_Email__c)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>External Id</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Non_Torc_User__c/fields/Quick_Books_vendor_Id__c.field-meta.xml
<CustomField>
    <fullName>Quick_Books_vendor_Id__c</fullName>
    <label>Quick Books vendor Id</label>
    <length>80</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Non_Torc_User__c/fields/Quickbooks_Vendor__c.field-meta.xml
<CustomField>
    <fullName>Quickbooks_Vendor__c</fullName>
    <label>Quickbooks Vendor</label>
    <length>80</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Non_Torc_User__c/fields/Trolley_Recipient__c.field-meta.xml
<CustomField>
    <fullName>Trolley_Recipient__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Trolley Recipient</label>
    <referenceTo>Trolley_Recipient__c</referenceTo>
    <relationshipLabel>Non Torc Users</relationshipLabel>
    <relationshipName>Non_Torc_Users</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Payment_Date__c/Payment_Date__c.object-meta.xml
<CustomObject>
    <label>QB Payment Date</label>
    <nameField>
        <displayFormat>Day-{0000}</displayFormat>
        <label>Payment Date Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>QB Payment Dates</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Torc_Constants__c/Torc_Constants__c.object-meta.xml
<CustomObject>
    <customSettingsType>Hierarchy</customSettingsType>
    <label>Torc Constants</label>
</CustomObject>

force-app/main/default/objects/Torc_Constants__c/fields/Trolley_Payment_batch_Size__c.field-meta.xml
<CustomField>
    <fullName>Trolley_Payment_batch_Size__c</fullName>
    <label>Trolley Payment batch Size</label>
    <precision>3</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Trolley_Batch__c/Trolley_Batch__c.object-meta.xml
<CustomObject>
    <label>Trolley Batch</label>
    <nameField>
        <displayFormat>batch-{000000}</displayFormat>
        <label>Trolley Batch Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Trolley Batchs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Trolley_Batch__c/fields/For_Non_Torc_User__c.field-meta.xml
<CustomField>
    <fullName>For_Non_Torc_User__c</fullName>
    <defaultValue>false</defaultValue>
    <label>For Non Torc User</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Trolley_Batch__c/fields/Total_Amount__c.field-meta.xml
<CustomField>
    <fullName>Total_Amount__c</fullName>
    <label>Total Amount</label>
    <summarizedField>Trolley_Invoice__c.Amount__c</summarizedField>
    <summaryForeignKey>Trolley_Invoice__c.Trolley_Batch__c</summaryForeignKey>
    <summaryOperation>sum</summaryOperation>
    <type>Summary</type>
</CustomField>

force-app/main/default/objects/Trolley_Invoice__c/Trolley_Invoice__c.object-meta.xml
<CustomObject>
    <label>Trolley Invoice</label>
    <nameField>
        <displayFormat>{0000000}</displayFormat>
        <label>Trolley Invoice Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Trolley Invoices</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Trolley_Invoice__c/fields/Amount__c.field-meta.xml
<CustomField>
    <fullName>Amount__c</fullName>
    <label>Amount</label>
    <precision>10</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Trolley_Invoice__c/fields/Cover_Fee__c.field-meta.xml
<CustomField>
    <fullName>Cover_Fee__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Cover Fee</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Trolley_Invoice__c/fields/Memo__c.field-meta.xml
<CustomField>
    <fullName>Memo__c</fullName>
    <label>Memo</label>
    <length>2000</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Trolley_Invoice__c/fields/Non_Torc_User__c.field-meta.xml
<CustomField>
    <fullName>Non_Torc_User__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Non Torc User</label>
    <referenceTo>Non_Torc_User__c</referenceTo>
    <relationshipLabel>Trolley Invoices</relationshipLabel>
    <relationshipName>Trolley_Invoices</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Trolley_Invoice__c/fields/Pass_Number__c.field-meta.xml
<CustomField>
    <fullName>Pass_Number__c</fullName>
    <label>Pass Number</label>
    <precision>3</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Trolley_Invoice__c/fields/Trolley_Batch__c.field-meta.xml
<CustomField>
    <fullName>Trolley_Batch__c</fullName>
    <label>Trolley Batch</label>
    <referenceTo>Trolley_Batch__c</referenceTo>
    <relationshipLabel>Trolley Invoices</relationshipLabel>
    <relationshipName>Trolley_Invoices</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Trolley_Invoice__c/fields/Trolley_Recipient__c.field-meta.xml
<CustomField>
    <fullName>Trolley_Recipient__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Trolley Recipient</label>
    <referenceTo>Trolley_Recipient__c</referenceTo>
    <relationshipLabel>Trolley Invoices</relationshipLabel>
    <relationshipName>Trolley_Invoices</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Trolley_Invoice_Line_Item__c/Trolley_Invoice_Line_Item__c.object-meta.xml
<CustomObject>
    <label>Trolley Invoice Line Item</label>
    <nameField>
        <displayFormat>TP-{0000000}</displayFormat>
        <label>Trolley Payment Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Trolley Invoice Line Items</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Trolley_Invoice_Line_Item__c/fields/Non_Torc_User__c.field-meta.xml
<CustomField>
    <fullName>Non_Torc_User__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Non Torc User</label>
    <referenceTo>Non_Torc_User__c</referenceTo>
    <relationshipLabel>Trolley Invoice Line Items</relationshipLabel>
    <relationshipName>Trolley_Invoice_Line_Items</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Trolley_Invoice_Line_Item__c/fields/Trolley_Batch__c.field-meta.xml
<CustomField>
    <fullName>Trolley_Batch__c</fullName>
    <label>Trolley Batch</label>
    <referenceTo>Trolley_Batch__c</referenceTo>
    <relationshipName>Trolley_Payments</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Trolley_Invoice_Line_Item__c/fields/Trolley_Invoice__c.field-meta.xml
<CustomField>
    <fullName>Trolley_Invoice__c</fullName>
    <label>Trolley Invoice</label>
    <referenceTo>Trolley_Invoice__c</referenceTo>
    <relationshipLabel>Trolley Invoice Line Items</relationshipLabel>
    <relationshipName>Trolley_Invoice_Line_Items</relationshipName>
    <relationshipOrder>1</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Trolley_Invoice_Line_Item__c/fields/Trolley_Recipient__c.field-meta.xml
<CustomField>
    <fullName>Trolley_Recipient__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Trolley Recipient</label>
    <referenceTo>Trolley_Recipient__c</referenceTo>
    <relationshipName>Trolley_Payments</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Trolley_Recipient__c/Trolley_Recipient__c.object-meta.xml
<CustomObject>
    <label>Trolley Recipient</label>
    <nameField>
        <label>Trolley Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Trolley Recipients</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Trolley_Recipient__c/fields/external_Id__c.field-meta.xml
<CustomField>
    <fullName>external_Id__c</fullName>
    <externalId>true</externalId>
    <label>external Id</label>
    <length>80</length>
    <required>true</required>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/Trolley_Recipient__c/fields/Full_Name__c.field-meta.xml
<CustomField>
    <fullName>Full_Name__c</fullName>
    <formula>First_Name__c+&apos; &apos;+ Last_Name__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Full Name</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Trolley_Recipient__c/fields/Non_Torc_User__c.field-meta.xml
<CustomField>
    <fullName>Non_Torc_User__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Non Torc User</label>
    <referenceTo>Non_Torc_User__c</referenceTo>
    <relationshipLabel>Trolley Recipients</relationshipLabel>
    <relationshipName>Trolley_Recipients</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Trolley_Recipient__c/fields/Payout_Method__c.field-meta.xml
<CustomField>
    <fullName>Payout_Method__c</fullName>
    <label>Payout Method</label>
    <length>40</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Trolley_Recipient__c/fields/referenceId__c.field-meta.xml
<CustomField>
    <fullName>referenceId__c</fullName>
    <label>referenceId</label>
    <length>80</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Trolley_Recipient__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <length>80</length>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/TrolleyNonQBPayments.cls
Public class TrolleyNonQBPayments
{
    public string showRowsType{get;set;}
    public List<SelectOption> getShowTypes()
    {
        List<SelectOption> ifPicklist = new List<SelectOption> ();
        ifPicklist.add(new SelectOption('All','All'));
        ifPicklist.add(new SelectOption('Error','Error'));
        ifPicklist.add(new SelectOption('Non-Error','Non-Error'));
        return ifPickList;
    }
    public List<DataRow> getshowableRows()
    {
        List<DataRow> l=new List<DataRow>();
        for(DataRow dr:lstDataRow)
        {
            if(showRowsType=='All' 
                || (showRowsType=='Error' && dr.getIsError()) 
                || (showRowsType=='Non-Error' && dr.getIsError()==FALSE))
            {
                l.add(dr);
            } 
        }
        return l;
    }
    public class processedRow
    {
        public Non_Torc_payment__c externalplacement{get;set;}
        public Trolley_Invoice__c tinv{get;set;}
        public Non_Torc_User__c nontorcuser{get;set;}
        public Trolley_recipient__c trolleyuser{get;set;}
        public List<Trolley_Invoice_Line_Item__c> lstpayment{get;set;}
        public string getrealName()
        {
            if(trolleyuser.Name==trolleyuser.Full_Name__c)
                return trolleyuser.Full_Name__c;
            else
                return trolleyuser.Name+' ('+trolleyuser.Full_Name__c+')';    
        }
        public processedRow(DataRow dr)
        {
            externalplacement = dr.extBill;
            nontorcuser = dr.nontorcuser;
            trolleyuser = dr.recipient;            
            lstpayment = new List<Trolley_Invoice_Line_Item__c>();
            tinv = new Trolley_Invoice__c();
            tinv.Trolley_Recipient__c = dr.recipient.id;
            tInv.Cover_Fee__c = true;
            tinv.non_Torc_user__c =dr.nontorcUser.id;
        }
        public decimal getTotal()
        {
            Decimal tot=0;
            for(Trolley_Invoice_Line_Item__c b: lstPayment)
            {
                tot +=b.Amount__c;
            }
            return tot;
        }
    }
    public class DataRow
    {
        public DataRow(Non_Torc_payment__c b,Trolley_Recipient__c tp)
        {
            chk = false;
            extbill=b;
            recipient=tp;
            nontorcUser = b.Non_Torc_user__r;
            dummy = new Dummy_Object__c();
        }
        
        public Non_Torc_payment__c extbill{get;set;}
        Public Trolley_Recipient__c recipient{get;set;}
        Public non_Torc_user__c nontorcUser{get;set;}
        Public Dummy_Object__c dummy{get;set;}
        public boolean chk{get;set;}
        public string geterrormsg()
        {
            return
                recipient==NULL?'No trolley recipient':
                recipient.status__c!='active'?'Trolley recipient inactive':
                nontorcuser.Quick_Books_vendor_Id__c==NULL || nontorcuser.Quick_Books_vendor_Id__c ==''?'QB Not Setup':'';
                
        }
        public boolean getIsError()
        {
            return recipient==NULL || recipient.status__c!='active' || nontorcuser.Quick_Books_vendor_Id__c==NULL || nontorcuser.Quick_Books_vendor_Id__c ==''; 
        }
         public List<Trolley_Invoice_Line_Item__c> getPaymentRecord()
         {
             List<Trolley_Invoice_Line_Item__c> ltp=new List<Trolley_Invoice_Line_Item__c>();
             Trolley_Invoice_Line_Item__c tp=new Trolley_Invoice_Line_Item__c();
             tp.amount__c = extbill.Total_Amount__c;
             tp.Non_Torc_user__c=nontorcuser.id;
             tp.Trolley_Recipient__c = recipient.id;
             Datetime dt=Datetime.newinstance(extBill.For_Month__c.year(),extBill.For_Month__c.month(),1);
             tp.description__c = nonTorcuser.Account__r.Name + ' Payout '+dt.format('MMMM yyyy');
             ltp.add(tp);
             return ltp;
         }
    }
    public List<Non_Torc_payment__c> lstExternalPlacement{get;set;}
    Public List<Payment_Date__c> lstPaymentDates;
    public List<DataRow> lstDataRow{get;set;}    
    public TrolleyNonQBPayments(ApexPages.StandardController controller)
    {
        lstDataRow = new List<DataRow>();
        EngagementOpportunity=(Opportunity) controller.getRecord(); 
        filter();
    }
    public void filter()
    {
        showRowsType='All';
        lstDataRow.clear();
        refresh();
    }
    public void refresh()
    {
        EngagementOpportunity = [Select ID,CloseDate,Account.Name,
                            (SELECT Id, Name, For_Month__c, Account__c, Payment_Created__c, Non_Torc_User__r.Account__r.Name,
                                    Total_Amount__c, Friendly_Name__c, Talent_Username__c, 
                                    Non_Torc_User__c, Non_Torc_User__r.Quick_Books_vendor_Id__c, Non_Torc_User__r.Quickbooks_Vendor__c,
                                    Non_Torc_User__r.External_Id__c
                                    ,Non_Torc_User__r.Name,Non_Torc_user__r.Custom_Memo_On_Payment__c
                             from Non_Torc_payments__r Where  Payment_Created__c=FALSE)
                             FROM Opportunity where id =:EngagementOpportunity.id];
                             
                             
                             /*,Non_Torc_User__r.Multi_Account_Payment__c, 
                                    Non_Torc_User__r.First_Payment_AccountID__c, 
                                    Non_Torc_User__r.Second_Payment_AccountID__c,
                                    Non_Torc_User__r.First_Payment_Account_Percent__c*/
                             
        lstExternalPlacement=EngagementOpportunity.Non_Torc_payments__r;
        showProcessed  = false;
        Set<id> nonTorcIds = new set<id>();
        for(Non_Torc_payment__c ep:lstExternalPlacement)
        {
            nonTorcIds.add(ep.Non_Torc_user__c);
        }
        Map<id, Trolley_Recipient__c > trMap=new Map<id, Trolley_Recipient__c >();
        for(Trolley_Recipient__c tr:[Select ID, Payout_Method__c,Full_Name__c, 
                                        Non_Torc_User__c,referenceId__C, Status__c,Name 
                                        from Trolley_Recipient__c 
                                        where Non_Torc_User__c in:nonTorcIds])
        {
            trMap.put(tr.Non_Torc_User__c,tr);
        }
        for(Non_Torc_payment__c ep: lstExternalPlacement)
        {
            DataRow bdr = new DataRow(ep,trMap.get(ep.Non_Torc_user__c));                    
            lstDataRow.add(bdr);
        }
    }
    Public List<ProcessedRow> processedRows{get;set;}
    public boolean showProcessed{get;set;}
    public Trolley_Batch__c trolleyBatch{get;set;}
    public Opportunity EngagementOpportunity{get;set;}
    public void back()
    {
        showProcessed=false;
    } 
    public decimal totalPayment{get;set;}
    public void next()
    {
        totalPayment = 0;
        trolleyBatch = new Trolley_Batch__c();
        trolleyBatch.For_Non_Torc_User__c = true;
        processedRows=new List<ProcessedRow>();
        Map<string,ProcessedRow> mapRecToTP = new Map<string,ProcessedRow>();
        for(dataRow dr : lstDataRow)
        {
            if(dr.chk)
            {
                    ProcessedRow newRec = new ProcessedRow(dr);
                    mapRecToTP.put(dr.recipient.id,newRec);
                    processedRows.add(newRec);
                    newRec.lstPayment.addAll(dr.getPaymentRecord());
                    showProcessed = true;    
            }
        }
        if(processedRows.size()==0)
        {
            ApexPages.addmessage(new ApexPages.message(ApexPages.severity.Error,'Please select atleast one valid row.'));
        }
        else
        {
        
            DateTime dt = date.today();
            trolleyBatch.Description__c = EngagementOpportunity.Account.Name + ' Payouts due on '+dt.format('dd MMMM yyyy');
            for(string repid:mapRecToTP.keyset())
            {
                string memo='';
                for(Trolley_Invoice_Line_Item__c tp:mapRecToTP.get(repId).lstPayment)
                {
                    memo = memo +(memo==''?'':', ')+tp.Description__c;
                }
                if(mapRecToTP.get(repid).nonTorcuser.Custom_Memo_On_Payment__c!=NULL && mapRecToTP.get(repid).nonTorcuser.Custom_Memo_On_Payment__c!='')
                        memo = mapRecToTP.get(repid).nonTorcuser.Custom_Memo_On_Payment__c;
                mapRecToTP.get(repid).tinv.memo__c = memo;
                totalPayment += mapRecToTP.get(repId).getTotal();
            }
            showProcessed=true;
        }
    }
    public Pagereference CreatePaymentsInTrolleyNew()
    {
        insert trolleyBatch;
        List<Trolley_Invoice__c> lstInv = new List<Trolley_Invoice__c>();
        List<Non_Torc_payment__c> extPList=new List<Non_Torc_payment__c>();
        integer passNumber = 0;
        integer rows = 0;
        for(processedRow pr:processedRows)
        {
            pr.tInv.Trolley_Batch__c = trolleyBatch.id;
            pr.tInv.pass_Number__c = passNumber;
            rows++;
            if(rows>= Torc_Constants__c.getInstance().Trolley_Payment_batch_Size__c)
            {
                rows=0;
                passNumber++;
            }
            lstInv.add(pr.tInv);
            extPList.add(new Non_Torc_payment__c(id=pr.externalPlacement.id, Payment_Created__c =true));
        }
        insert lstInv;
        List<Trolley_Invoice_Line_Item__c> lstpaymentsINV = new List<Trolley_Invoice_Line_Item__c >();
        for(processedRow pr:processedRows)
        {
            for(Trolley_Invoice_Line_Item__c tp:pr.lstPayment)
            {
                tp.Trolley_Batch__c = trolleyBatch.id;
                tp.Trolley_Invoice__c = pr.tInv.id;
            }
            lstpaymentsINV.addAll(pr.lstPayment);
        } 
        insert lstpaymentsINV;
        upsert extPList;
        TrolleyAPICallQueue.runProcess(trolleyBatch.id);
        return new Pagereference('/'+trolleyBatch.id);
    }
    Public void reloadRecipient()
    {
        loadRecipient();
    }
    Public static void loadRecipient()
    {
        TrolleyReceipientQueue.runProcess(test.isRunningTest());
    }
    public void dummyCall()
    {
    }
}