force-app/main/default/objects/Dummy_Object__c/Dummy_Object__c.object-meta.xml
<CustomObject>
    <description>Temporary object used for display in VF pages</description>
    <label>Dummy Object</label>
    <nameField>
        <displayFormat>D-{00}</displayFormat>
        <label>Dummy Object Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Dummy Object</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Dummy_Object__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Dummy Object</relationshipLabel>
    <relationshipName>Dummy_Object</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Dummy_Object__c/fields/Opportunity__c.field-meta.xml
<CustomField>
    <fullName>Opportunity__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Opportunity</label>
    <referenceTo>Opportunity</referenceTo>
    <relationshipLabel>Dummy Object</relationshipLabel>
    <relationshipName>Dummy_Object</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Non_Torc_Payment__c/Non_Torc_Payment__c.object-meta.xml
<CustomObject>
    <label>Non Torc Payment</label>
    <nameField>
        <label>Payment Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Non Torc Payments</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Non_Torc_Payment__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Non Torc Payments</relationshipLabel>
    <relationshipName>Non_Torc_Payments</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Non_Torc_Payment__c/fields/Bank_Fee__c.field-meta.xml
<CustomField>
    <fullName>Bank_Fee__c</fullName>
    <label>Bank Fee</label>
    <precision>12</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Non_Torc_Payment__c/fields/For_Month__c.field-meta.xml
<CustomField>
    <fullName>For_Month__c</fullName>
    <label>For Month</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Non_Torc_Payment__c/fields/Non_Torc_User__c.field-meta.xml
<CustomField>
    <fullName>Non_Torc_User__c</fullName>
    <label>Non Torc User</label>
    <referenceTo>Non_Torc_User__c</referenceTo>
    <relationshipLabel>Non Torc Payments</relationshipLabel>
    <relationshipName>Non_Torc_Payments</relationshipName>
    <relationshipOrder>1</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Non_Torc_Payment__c/fields/Opportunity__c.field-meta.xml
<CustomField>
    <fullName>Opportunity__c</fullName>
    <label>Opportunity</label>
    <referenceTo>Opportunity</referenceTo>
    <relationshipLabel>Non Torc Payments</relationshipLabel>
    <relationshipName>Non_Torc_Payments</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Non_Torc_Payment__c/fields/Opportunity_Product__c.field-meta.xml
<CustomField>
    <fullName>Opportunity_Product__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Opportunity Product</label>
    <referenceTo>OpportunityLineItem</referenceTo>
    <relationshipLabel>Non Torc Payments</relationshipLabel>
    <relationshipName>Non_Torc_Payments</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Non_Torc_Payment__c/fields/Payment_Created__c.field-meta.xml
<CustomField>
    <fullName>Payment_Created__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Payment Created</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Non_Torc_Payment__c/fields/Torc_Fee__c.field-meta.xml
<CustomField>
    <fullName>Torc_Fee__c</fullName>
    <label>Torc Fee</label>
    <precision>12</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Non_Torc_Payment__c/fields/Total_Amount__c.field-meta.xml
<CustomField>
    <fullName>Total_Amount__c</fullName>
    <label>Total Amount</label>
    <precision>12</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Non_Torc_User__c/Non_Torc_User__c.object-meta.xml
<CustomObject>
    <label>Non Torc User</label>
    <nameField>
        <label>Non Torc User Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Non Torc Users</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Non_Torc_User__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Non Torc Users</relationshipLabel>
    <relationshipName>Non_Torc_Users</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Non_Torc_User__c/fields/Contact__c.field-meta.xml
<CustomField>
    <fullName>Contact__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Contact</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Non Torc Users</relationshipLabel>
    <relationshipName>Non_Torc_Users</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Non_Torc_User__c/fields/Default_Monthly_Rate__c.field-meta.xml
<CustomField>
    <fullName>Default_Monthly_Rate__c</fullName>
    <label>Default Monthly Rate</label>
    <precision>10</precision>
    <required>true</required>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Non_Torc_User__c/fields/Docusign_Status__c.field-meta.xml
<CustomField>
    <fullName>Docusign_Status__c</fullName>
    <formula>IF( Explicit_Docusign_Mark_Complete__c ,&apos;Completed&apos;,
IF( Latest_DocuSign_Status__c = NULL,&apos;Not Sent&apos;,  Latest_DocuSign_Status__r.dfsle__Status__c ))</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Docusign Status</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Non_Torc_User__c/fields/Engagement_Months__c.field-meta.xml
<CustomField>
    <fullName>Engagement_Months__c</fullName>
    <defaultValue>12</defaultValue>
    <label>Engagement Months</label>
    <precision>3</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Non_Torc_User__c/fields/Family_Name__c.field-meta.xml
<CustomField>
    <fullName>Family_Name__c</fullName>
    <label>Family Name</label>
    <length>80</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Non_Torc_User__c/fields/First_Month__c.field-meta.xml
<CustomField>
    <fullName>First_Month__c</fullName>
    <label>Engagement Start Date</label>
    <required>true</required>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Non_Torc_User__c/fields/Given_Name__c.field-meta.xml
<CustomField>
    <fullName>Given_Name__c</fullName>
    <label>Given Name</label>
    <length>80</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Non_Torc_User__c/fields/Monthly_USD_Expense__c.field-meta.xml
<CustomField>
    <fullName>Monthly_USD_Expense__c</fullName>
    <label>Monthly USD Expense</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Non_Torc_User__c/fields/Official_Email__c.field-meta.xml
<CustomField>
    <fullName>Official_Email__c</fullName>
    <label>Official Email</label>
    <type>Email</type>
</CustomField>

force-app/main/default/objects/Non_Torc_User__c/fields/Payment_Start_Date__c.field-meta.xml
<CustomField>
    <fullName>Payment_Start_Date__c</fullName>
    <label>Payment Start Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Non_Torc_User__c/fields/Position__c.field-meta.xml
<CustomField>
    <fullName>Position__c</fullName>
    <label>Position</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Data Developer</fullName>
            </value>
            <value>
                <fullName>Delivery Manager</fullName>
            </value>
            <value>
                <fullName>Engineering Developer</fullName>
            </value>
            <value>
                <fullName>Lead Mobile developer</fullName>
            </value>
            <value>
                <fullName>Location Manager</fullName>
            </value>
            <value>
                <fullName>Machine Learning Senior</fullName>
            </value>
            <value>
                <fullName>Mobile Developer</fullName>
            </value>
            <value>
                <fullName>Project Manager</fullName>
            </value>
            <value>
                <fullName>Quality Assurance</fullName>
            </value>
            <value>
                <fullName>Talent Acquisition Specialist</fullName>
            </value>
            <value>
                <fullName>UX/UI Designer</fullName>
            </value>
            <value>
                <fullName>Site Reliability Engineering</fullName>
            </value>
            <value>
                <fullName>Firmware</fullName>
            </value>
            <value>
                <fullName>Cybersecurity</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Non_Torc_User__c/fields/Trolley_Recipient__c.field-meta.xml
<CustomField>
    <fullName>Trolley_Recipient__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Trolley Recipient</label>
    <referenceTo>Trolley_Recipient__c</referenceTo>
    <relationshipLabel>Non Torc Users</relationshipLabel>
    <relationshipName>Non_Torc_Users</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Non_Torc_User__c/fields/Trolley_Status__c.field-meta.xml
<CustomField>
    <fullName>Trolley_Status__c</fullName>
    <formula>IF( Trolley_Recipient__c = NULL,&apos;Not Created&apos;, Trolley_Recipient__r.Status__c )</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Payment Profile</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Qubika_Employee__c/Qubika_Employee__c.object-meta.xml
<CustomObject>
    <label>Qubika Portal Employee</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Qubika Portal Employees</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Qubika_Employee__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipName>Qubika_Employees</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Qubika_Employee__c/fields/Profile__c.field-meta.xml
<CustomField>
    <fullName>Profile__c</fullName>
    <label>Profile</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Admin</fullName>
            </value>
            <value>
                <fullName>SalaryData</fullName>
            </value>
            <value>
                <fullName>UserData</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Qubika_Employee__c/fields/Verification_Code__c.field-meta.xml
<CustomField>
    <fullName>Verification_Code__c</fullName>
    <label>Verification Code</label>
    <length>4</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Qubika_Verification__c/Qubika_Verification__c.object-meta.xml
<CustomObject>
    <label>Qubika Verification</label>
    <nameField>
        <displayFormat>V-{000000}</displayFormat>
        <label>Qubika Verification ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Qubika Verification</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Qubika_Verification__c/fields/User_Name__c.field-meta.xml
<CustomField>
    <fullName>User_Name__c</fullName>
    <label>User Name</label>
    <length>80</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Torc_Constants__c/Torc_Constants__c.object-meta.xml
<CustomObject>
    <customSettingsType>Hierarchy</customSettingsType>
    <label>Torc Constants</label>
</CustomObject>

force-app/main/default/objects/Torc_Constants__c/fields/Qubika_Account__c.field-meta.xml
<CustomField>
    <fullName>Qubika_Account__c</fullName>
    <label>Qubika Account</label>
    <length>40</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Trolley_Recipient__c/Trolley_Recipient__c.object-meta.xml
<CustomObject>
    <label>Trolley Recipient</label>
    <nameField>
        <label>Trolley Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Trolley Recipients</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Trolley_Recipient__c/fields/Estimated_Fee__c.field-meta.xml
<CustomField>
    <fullName>Estimated_Fee__c</fullName>
    <label>Estimated Fee</label>
    <precision>7</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Trolley_Recipient__c/fields/Non_Torc_User__c.field-meta.xml
<CustomField>
    <fullName>Non_Torc_User__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Non Torc User</label>
    <referenceTo>Non_Torc_User__c</referenceTo>
    <relationshipLabel>Trolley Recipients</relationshipLabel>
    <relationshipName>Trolley_Recipients</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Trolley_Recipient__c/fields/Payout_Method__c.field-meta.xml
<CustomField>
    <fullName>Payout_Method__c</fullName>
    <label>Payout Method</label>
    <length>40</length>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/QubikaOperation.cls
Public Without Sharing Class QubikaOperation
{
    public string loadType{get;set;}
    public Dummy_Object__c dummyDate{get;set;}
    public List<googleAPI.paymentCls> lstPayments{get;set;}
    public List<googleAPI.rowCls> lstContacts{get;set;}
    public Account account{get;set;}
    public Opportunity opp{get;set;}
    public opportunityLineItem oppLineItem{get;set;}
    public string warningMessage{get;set;}
    Public List<String>ErrorList{get;set;}
    public QubikaOperation()
    {    
        ErrorList=new List<String>();
        //emailaddress='sumit@torc.dev';
        emailaddress='';
        LoggedInUserName = 'Guest';
        dateTime dt = Datetime.newInstance(date.Today().year(),date.Today().Month(),5);
        selectedDate = dt.month()+'-'+dt.year();
        id currentUser = UserInfo.getuserId();
        user u=[Select Id, Profile.Name,Name,Torc_Admin__c from User where id=:currentUser];
        if(u.Profile.Name=='System Administrator' || u.Torc_Admin__c==true)
        {
            usertype = 'SuperAdmin';
            LoggedInUserName = u.Name;
        }
        ELSE if(u.Profile.Name=='Torc Employee' || u.Profile.Name=='Torc Executive')    
        {
            usertype = 'Internal';
            LoggedInUserName = u.Name;
        }
        ELSE
            usertype = 'EXTERNAL';    
        
        //usertype = 'Admin';
        dummyDate= new Dummy_Object__c();
        dummyDate.Date__c = Date.newInstance(Date.today().year(),Date.today().month(),1);
        lstPayments = new List<googleAPI.paymentCls>();
        lstContacts = new List<googleAPI.rowCls>();
        account = [Select ID from Account Where id=:Torc_Constants__c.getInstance().Qubika_Account__c];
        if(userType=='EXTERNAL')
            screen = 'LOGIN';
        else
            screen = 'DATA';    
    }
    public static string getOpportunityName(Date dt)
    {
        return 'Qubika ' + dt.month().toString().leftpad(2,'0')+'/'+dt.year();
    }
    Public boolean loadOpportunityAndLineItem()
    {
        ErrorList.clear();
        Date dt1 = Date.newInstance(dummyDate.Date__c.year(),dummyDate.Date__c.month(),10).addmonths(1);
        dt1 = Date.newInstance(dt1.year(),dt1.month(),1).adddays(-1);
        opp=NULL;
        for(Opportunity op:[SELECT Id, Name, Closedate,StageName, AccountId,Account.Name,
                                (Select ID ,Engagement_Start_Date__c, Customer_Hourly_Bill_Rate__c ,Unitprice,TotalPrice,OpportunityId
                                    FROM OpportunityLineItems where Product2.name='Transaction Fee'),
                                (Select ID from Non_Torc_payments__r where Payment_Created__c=TRUE LIMIT 1)                                    
                            FROM Opportunity 
                            WHERE AccountId=:account.id and CloseDate=:dt1 order by createddate desc LIMIT 1])
        {
            opp=op;
        }
        if(opp==NULL)
        {
            opp=new Opportunity(AccountId=account.id,Name=getOpportunityName(dt1),CloseDate = dt1,StageName='Need Posted');
        }
        if(opp.Non_Torc_payments__r.size()>0)
        {
             ErrorList.add('There are already some payments marked paid. Please contact torc support.');
             return true;
        }
        
        if([Select Id from Non_Torc_payment__c where Opportunity__c=:opp.id LIMIT 1].size()>0)
        {
            warningMessage = 'There are already payments created for this month. Nothing is marked paid yet. So this process will delete existing records.';
        }
        if(opp.OpportunityLineItems.size()==0)
        {
            id priceBookID = [SELECT Id FROM Pricebook2 WHERE IsStandard = true LIMIT 1].Id;
            PricebookEntry pbe = [Select Id, IsActive,Product2Id, Product2.Name, Product2.ProductCode,Product2.Description, UnitPrice
                                from PricebookEntry
                                where Pricebook2Id=:priceBookID
                                AND Product2.Name='Transaction Fee'];
            Date dt = Date.newInstance(Opp.Closedate.year(),Opp.Closedate.Month(),1);
            oppLineItem=new opportunityLineItem(Engagement_Start_Date__c=dt,
                                                Quantity=1,
                                                Product2Id = pbe.Product2Id,priceBookEntryID= pbe.id,
                                                Product_Type__c = 'Transaction Fee',
                                                Hours_Week__c=1,
                                                Engagement_End_Date__c = dt.adddays(7),
                                                Engagement_Duration_weeks__c=1,
                                                Time_Commitment__c = 'HALFTIME',
                                                Talent_Hourly_Pay_Rate__c=0
                                                );
                                        
        }   
        else
            oppLineItem = opp.OpportunityLineItems[0];
        return false;    
    }
    public void back()
    {
        ErrorList.clear();
        loadType='';
        showRowsType='All';
        fileName='';
        file=null;
    }
    public void updateContacts()
    {
        ErrorList.clear();
        List<Non_Torc_user__c> l=new List<Non_Torc_user__c>();
        for(googleAPI.rowCls r:lstContacts)
        {
            l.add(r.user);
        }
        if(l.size()>0)
            Upsert l;
        lstContacts.clear(); 
        loadType='';   
    }
    public void updatePayments()
    {
        ErrorList.clear();
        If(opp.Id==NULL)
            upsert opp;
        if(oppLineItem.OpportunityId==NULL)    
            oppLineItem.OpportunityId = opp.id;
            
        decimal tf=0;
        for(List< Non_Torc_payment__c >l:[Select id from Non_Torc_payment__c where Opportunity__c=:opp.id])
            delete l;
        List< Non_Torc_payment__c >newList=new List< Non_Torc_payment__c >();    
        for(googleAPI.paymentCls r:lstPayments)
        {
            if(r.chk)
            {
                tf +=r.payRec.Torc_fee__c;
                newList.add(r.payRec);
            }    
        }
        oppLineItem.UnitPrice = tf;
        oppLineItem.Bank_fee__c = getTotalbankFee();
        oppLineItem.Customer_Hourly_Bill_Rate__c = tf;
        upsert oppLineItem;
        for(Non_Torc_payment__c a:newlist)
        {
            a.Opportunity_Product__c = oppLineItem.id;
            a.Opportunity__c = opp.id;
            a.Account__c = opp.AccountId;
            a.For_Month__c = oppLineItem.Engagement_Start_Date__c;
        }
        insert newList;
        lstPayments.clear();
        loadType='';
    }
    public decimal getTotalbankFee()
    {
        Decimal paypalAmount = 0;
        Decimal amt=0;
        for(googleAPI.paymentCls r:lstPayments)
        {
            if(r.chk)
            {
                amt +=r.payRec.Bank_fee__c;
                if(r.isPaypal)
                {
                    paypalAmount += r.total;
                }    
            }    
        }
        if(paypalAmount >=1000)
            amt +=20;
        else
            amt +=(paypalAmount*0.02);    
        return amt;
    }
    
    public decimal getTotalTorcFee()
    {
        Decimal amt=0;
        for(googleAPI.paymentCls r:lstPayments)
        {
            if(r.chk)
                amt +=r.payRec.Torc_fee__c;
        }
        return amt;
    }
    public decimal getTotalEmployeePayment()
    {
        Decimal amt=0;
        for(googleAPI.paymentCls r:lstPayments)
        {
            if(r.chk)
                amt +=r.payRec.Total_Amount__c;
        }
        return amt;
    }
    public void dummyCall(){}
    public string showRowsType{get;set;}
    public List<SelectOption> getShowTypes()
    {
        List<SelectOption> ifPicklist = new List<SelectOption> ();
        ifPicklist.add(new SelectOption('All','All'));
        ifPicklist.add(new SelectOption('Error','Error'));
        ifPicklist.add(new SelectOption('Non-Error','Non-Error'));
        return ifPickList;
    }
    
    public string selectedDate{get;set;}
    public List<SelectOption> getDates()
    {
        List<SelectOption> ifPicklist = new List<SelectOption> ();
        Datetime dt = Datetime.newInstance(date.Today().year(),date.Today().Month(),5);
        ifPicklist.add(new SelectOption(dt.month()+'-'+dt.year(),dt.format('MMMM-yyyy')));
        dt = Datetime.newInstance(datetime.now().year(),datetime.now().month()-1,5);
        ifPicklist.add(new SelectOption(dt.month()+'-'+dt.year(),dt.format('MMMM-yyyy')));
        return ifPickList;
    }
    public List<googleAPI.paymentCls> getshowableRows()
    {
        List<googleAPI.paymentCls> l=new List<googleAPI.paymentCls>();
        for(googleAPI.paymentCls dr:lstPayments)
        {
            if(showRowsType=='All' 
                || (showRowsType=='Error' && dr.getIsError()) 
                || (showRowsType=='Non-Error' && dr.getIsError()==FALSE))
            {
                l.add(dr);
            } 
        }
        return l;
    } 
    
    
    
    
    
    
//------------------------------------------------------------------------------------------------------------------------------------    
    public Blob file {get; set;}
    public String fileName {get; set;}
    public void loadpaymemntData() 
    {
        ErrorList.clear();
        loadType='PAYMENT';
        showRowsType='All';

        if(loadOpportunityAndLineItem())
        {
            return;
        }
        if(loadDataData('PAYMENT'))
        {
            loadType='';
            return;
        }
        map<string,googleAPI.paymentCls> emails=new map<string,googleAPI.paymentCls>();
        for(googleAPI.paymentCls r:lstPayments)
        {
            emails.put(r.OfficialEmail.toLowerCase().trim(),r);
        }
        for(Non_Torc_user__c ntr:[Select Id, Name, Monthly_USD_Expense__c, Default_Monthly_Rate__c, Official_Email__c, 
                                        Given_Name__c ,Family_Name__c, 
                                        Trolley_recipient__r.Estimated_fee__c,Trolley_Status__c,Docusign_Status__c, Trolley_recipient__r.Payout_Method__c
                                        FROM Non_Torc_user__c where Official_Email__c in:emails.keyset() AND account__c =: account.id])
        {
            emails.get(ntr.Official_Email__c.toLowercase()).setUser(ntr);
        }
        for(googleAPI.paymentCls r:lstPayments)
        {
            r.editData(opp,oppLineItem);
        }               
    }
    public void loadcontactData() 
    {
        ErrorList.clear();
        loadType='CONTACT';
        if(loadDataData('CONTACT'))
        {
            loadType='';
            return;    
        }
        map<string,googleAPI.rowCls> emails=new map<string,googleAPI.rowCls>();
        for(googleAPI.rowCls r:lstContacts)
        {
            emails.put(r.OfficialEmail.toLowerCase().trim(),r);
        }
        for(Non_Torc_user__c ntr:[Select Id, Name,  Payment_Start_Date__c, Given_Name__c, Family_Name__c, Email__c, Monthly_USD_Expense__c, 
                                        Account__c, Default_Monthly_Rate__c, 
                                        First_Month__c, Engagement_Months__c, 
                                        Contact__c, Official_Email__c, 
                                        Termination_Date__c, Country__c, Position__c 
                                        FROM Non_Torc_user__c where Official_Email__c in:emails.keyset()])
        {
            emails.get(ntr.Official_Email__c.toLowercase()).user = ntr;
        }
        for(googleAPI.rowCls r:lstContacts)
        {
            if(r.user==NULL)
            {
               r.user=new  Non_Torc_user__c(Account__c = account.id);
            }
            r.editData();
        }           
    }
    public boolean loadDataData(string type) 
    {
        ErrorList.clear();
        if(type=='PAYMENT')
            lstPayments.clear();
        if(type=='CONTACT')
            lstContacts.clear(); 
        if(fileName=='' || fileName==null)
        {
            ErrorList.add('Please click on browse button and select a valid csv file.');
            return true;
        }   
        String fileContent;    
        String[] lines;
        system.debug(file);
        try
        {
            fileContent = file.toString();
            lines = parseCsvLines(fileContent);
        }
        catch(Exception ex)
        {
            ErrorList.add('Looks Like you selecte a wrong file. This file is not a CSV...'+ex.getMessage());
            return true;
        }
        system.debug(fileContent);
        List<Map<String, String>> records = new List<Map<String, String>>();
        String[] headers = parseCsvLine(lines[0]);
        system.debug(headers);
        string missed = googleAPI.missingHeaders(headers,type);
        system.debug(missed);
        if(missed!='')
        {
            ErrorList.add('Few Important Fields are missing :' +missed);
            return true;
        }
        system.debug(lines.size());
        for (Integer i = 1; i < lines.size(); i++) 
        {
            String[] values = parseCsvLine(lines[i]);
            system.debug(values);
            if(type=='PAYMENT')
            {
                googleAPI.paymentCls row = new googleAPI.paymentCls();
                googleAPI.getPaymentRow(row,values,headers);
                lstPayments.add(row);
            }
            if(type=='CONTACT')
            {
                googleAPI.rowCls row = new googleAPI.rowCls();
                googleAPI.getContactRow(row,values,headers);
                lstContacts.add(row);
            }
        }
        system.debug(lstPayments);
        system.debug(lstContacts);
        return false;
    }
    private List<String> parseCsvLines(String csvContent) 
    {
        return csvContent.split('\n');
    }
    
    private String[] parseCsvLine(String line) 
    {
        List<String> values = new List<String>();
        String value = '';
        Boolean inQuotes = false;
        
        for (Integer i = 0; i < line.length(); i++) 
        {
            String c = line.substring(i, i + 1);
            if (c == '\"') 
            {
                inQuotes = !inQuotes; // Toggle the inQuotes flag
            } 
            else if (c == ',' && !inQuotes) 
            {
                values.add(value);
                value = '';
            } 
            else 
            {
                value += c;
            }
        }
        values.add(value); // Add the last value
        
        return values;
    }
    //--------------- Portal Implementation--------------------------------
    public string emailAddress{get;set;}
    public string usertype{get;set;}
    public string screen{get;set;}
    public string LoggedInUserName{get;set;}
    public string verificationID{get;set;}
    public boolean enteredinvalidCode{get;set;}
    private Qubika_Employee__c qEmployee{get;set;}
    
    public void backToLogin()
    {
        ErrorList.clear();
        screen='LOGIN';
    }
    public void VerifyEmailAddress()
    {
        ErrorList.clear();
        if(emailAddress==null || emailAddress.trim()=='')
        {
            ErrorList.add('Please provide your email address.');
            return;
        }
        
        List< Qubika_Employee__c> lst=[Select ID, Name, Email__c,Profile__c from Qubika_Employee__c where email__c=:emailAddress AND Account__c=:account.id];
        if(lst.size()>0)
        {
            qEmployee = lst[0];
            SendToverify();
        }
        else
        {
            ErrorList.add('You Are Not Authorised. Please contact Torc Support');
        }
    }
    public void SendToverify()
    {
        ErrorList.clear();
        enteredinvalidCode = false;
        verificationID='';
        verificationID = String.valueOf(Integer.valueOf(Math.random()*10));
        verificationID += String.valueOf(Integer.valueOf(Math.random()*10));
        verificationID += String.valueOf(Integer.valueOf(Math.random()*10));
        verificationID += String.valueOf(Integer.valueOf(Math.random()*10));
        qEmployee.Verification_Code__c = verificationID;
        Qubika_Verification__c tsv=new Qubika_Verification__c(Code__c=verificationID,Email__c = qEmployee.Email__c,User_Name__c = qEmployee.Name);
        insert tsv;        
        screen = 'VERIFY';
        verifycode1 = verifycode2 = verifycode3 =verifycode4 ='';
    }
    public string verifycode1{get;set;}
    public string verifycode2{get;set;}
    public string verifycode3{get;set;}
    public string verifycode4{get;set;}
    public void verifyCode()
    {
        ErrorList.clear();
        string verif = verifycode1+verifycode2+verifycode3+verifycode4;
        if(verif == qEmployee.Verification_Code__c)
        {   
            usertype = qEmployee.Profile__c;
            LoggedInUserName = qEmployee.Name; 
            screen = 'DATA';
        }
        else
        {
            ErrorList.add('You entered a wrong code. Please click on "resend new code" or change login email address.');
            enteredinvalidCode = true;
        }    
    }
}