force-app/main/default/objects/Dummy_Object__c/Dummy_Object__c.object-meta.xml
<CustomObject>
    <description>Temporary object used for display in VF pages</description>
    <label>Dummy Object</label>
    <nameField>
        <displayFormat>D-{00}</displayFormat>
        <label>Dummy Object Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Dummy Object</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Dummy_Object__c/fields/Torc_User__c.field-meta.xml
<CustomField>
    <fullName>Torc_User__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Torc User</label>
    <referenceTo>Torc_User__c</referenceTo>
    <relationshipLabel>Dummy Object</relationshipLabel>
    <relationshipName>Dummy_Object</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/QB_API_Call__c/QB_API_Call__c.object-meta.xml
<CustomObject>
    <label>QB API Call</label>
    <nameField>
        <label>Type</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>QB API Calls</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/QB_API_Call__c/fields/Delete__c.field-meta.xml
<CustomField>
    <fullName>Delete__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Delete?</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Torc_User__c/Torc_User__c.object-meta.xml
<CustomObject>
    <label>Torc User</label>
    <nameField>
        <label>Torc User Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Torc Users</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Torc_User__c/fields/Quick_Books_vendor_Id__c.field-meta.xml
<CustomField>
    <fullName>Quick_Books_vendor_Id__c</fullName>
    <label>Quick Books vendor Id</label>
    <length>80</length>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/QBBulkBillUpdate.cls
public class QBBulkBillUpdate
{
    public void pageToken()
    {
        QB_Authentication authentication = new QB_Authentication();
        authentication.initializeToken();
        authentication.persistTokenInDb();
    }
    public class DataRow
    {
        public QBAccountingService.QBBill Bill{get;set;}
        public boolean getEditable()
        {
            return QBOpportunitySetup.StringToDate(bill.duedate) > Date.today();
        }
        public DataRow(QBAccountingService.QBBill b)
        {
            bill=b;
        }
    }
    Public string step{get;set;}
    public List<DataRow> lstDataRow{get;set;}
    public Dummy_Object__c fromDate{get;set;}
    public Dummy_Object__c toDate{get;set;}
    Public Torc_User__c torcUser{get;set;}
    public QBBulkBillUpdate()
    {
        step = 'SELACT';
        fromDate = new Dummy_Object__c();
        toDate = new Dummy_Object__c();
        lstDataRow = new List<DataRow>();
        torcUser=null;
        if(ApexPages.currentPage().getParameters().get('id')!='' && ApexPages.currentPage().getParameters().get('id')!=NULL)
        {
            fromDate.Torc_user__c = ApexPages.currentPage().getParameters().get('id');
        }
    }
    public string filterFor{get;set;}
    public void filterForDeleteBill()
    {
        filterFor='DELETE';
        filterForBill();
    }
    public void filterForUpdateBill()
    {
        filterFor='UPDATE';
        filterForBill();
    }
    public void filterForBill()
    {
        lstDataRow.clear();
        Date sd = fromDate.Date__c;
        Date ed = toDate.Date__c;
        string vendorQBId='';
        if(fromDate.Torc_User__c!=NULL)
        {
            for(Torc_User__c tu:[SELECT id,Quick_Books_Vendor_Id__c from Torc_User__c WHERE ID=:fromDate.Torc_User__c])
            {
                torcUser = tu;
                if(tu.Quick_Books_Vendor_Id__c ==NULL || tu.Quick_Books_Vendor_Id__c =='')
                {
                    ApexPages.addmessage(new ApexPages.message(ApexPages.severity.Error,'Error:Please update QB ID Torc User First.'));
                    return;
                }                
                vendorQBId = tu.Quick_Books_Vendor_Id__c;
            }
        }
        step = 'SAVE';
        string query= 'SELECT * FROM Bill ';
        string cond ='';
        if(vendorQBId!=NULL && vendorQBID!='')
            cond =' WHERE VendorRef = \''+vendorQBID+'\''; 
        if(sd!=NULL)
            cond = cond +' '+  (cond==''?'WHERE':'AND') + ' TxnDate >= \''+ QBOpportunitySetup.DateToString(sd) +'\' ';
        if(ed!=NULL)
            cond = cond +' '+  (cond==''?'WHERE':'AND') + ' TxnDate <= \''+ QBOpportunitySetup.DateToString(ed) +'\' ';    
        query =query + cond + ' Order By TxnDate,DocNumber';
        lstDataRow.clear();
        system.debug(query);
        JSONParser jp = QBAccountingService.runQuery(query);
        QBAccountingService.QBResponseBill res=(QBAccountingService.QBResponseBill)jp.readValueAs(QBAccountingService.QBResponseBill.class);
        if(res.QueryResponse!=NULL && res.QueryResponse.bill!=NULL)
        {
            for(QBAccountingService.QBBill inv:res.QueryResponse.bill)
            {
                DataRow bdr = new DataRow(inv);
                lstDataRow.add(bdr);
            }    
        }
    }
    public void SaveUpdate()
    {
        List<QB_API_Call__c> lst=new List<QB_API_Call__c>();
        for(DataRow inv : lstDataRow)
        {
            QBAccountingService.QBBill bill =inv.bill;
            if(bill.selectedRow==TRUE)
            {
                QB_API_Call__c qb = new  QB_API_Call__c(Name='bill',Input__c = QBOpportunitySetup.removeAttributes(JSON.serialize(bill)));
                lst.add(qb);
            }     
        }
        if(lst.size()>0)
        {
            QBOpportunitySetup.CallQBAPI(lst);
            step = 'SELECT';    
        }
        else
        {
            ApexPages.addmessage(new ApexPages.message(ApexPages.severity.Error,'Error:Select Rows to delete.'));
            return;
        }    
    }
    public void SaveDelete()
    {
        List<QB_API_Call__c> lst=new List<QB_API_Call__c>();
        for(DataRow inv : lstDataRow)
        {
            QBAccountingService.QBBill bill =inv.bill;
            if(bill.selectedRow==TRUE)
            {
                 QB_API_Call__c qb = new  QB_API_Call__c(Delete__c=true, Name='bill',Input__c = QBOpportunitySetup.removeAttributes(JSON.serialize(bill)));
                 lst.add(qb);
            }     
        }
        if(lst.size()>0)
        {
            QBOpportunitySetup.CallQBAPI(lst);
            step = 'SELECT';    
        }
        else
        {
            ApexPages.addmessage(new ApexPages.message(ApexPages.severity.Error,'Error:Select Rows to delete.'));
            return;
        }    
    }
}