force-app/main/default/objects/Dummy_Object__c/Dummy_Object__c.object-meta.xml
<CustomObject>
    <description>Temporary object used for display in VF pages</description>
    <label>Dummy Object</label>
    <nameField>
        <displayFormat>D-{00}</displayFormat>
        <label>Dummy Object Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Dummy Object</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Dummy_Object__c/fields/Opportunity__c.field-meta.xml
<CustomField>
    <fullName>Opportunity__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Opportunity</label>
    <referenceTo>Opportunity</referenceTo>
    <relationshipLabel>Dummy Object</relationshipLabel>
    <relationshipName>Dummy_Object</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Torc_Constants__c/Torc_Constants__c.object-meta.xml
<CustomObject>
    <customSettingsType>Hierarchy</customSettingsType>
    <label>Torc Constants</label>
</CustomObject>

force-app/main/default/objects/Torc_Constants__c/fields/Qubika_Account__c.field-meta.xml
<CustomField>
    <fullName>Qubika_Account__c</fullName>
    <label>Qubika Account</label>
    <length>40</length>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/Qubika.cls
public class Qubika
{
    public Dummy_Object__c dummy{get;set;}
    public Qubika()
    {
        dummy=new Dummy_Object__c();
    }
    public Pagereference loadpaymentCSV()
    {
        return new Pagereference('/apex/qubikaoperation');
    }
    public Pagereference nonTorcTrolleySetup()
    {
        return new Pagereference('/apex/QBNonTorcSetup?id='+torc_Constants__c.getinstance().Qubika_Account__c);
    }
    public Pagereference loadUserGoogle()
    {
        return new Pagereference('/apex/loadQubikaData?id='+torc_Constants__c.getinstance().Qubika_Account__c);
    }
    
    public Pagereference loadPaymentGoogle()
    {
        return new Pagereference('/apex/nonTorcpayment?id='+dummy.Opportunity__c);
    }
    public Pagereference DoPayment()
    {
        return new Pagereference('/apex/TrolleyNonQBPayments?id='+dummy.Opportunity__c);
    }
    
    

}