force-app/main/default/objects/Freelancer_Questionnaire__c/Freelancer_Questionnaire__c.object-meta.xml
<CustomObject>
    <label>Freelancer Questionnaire</label>
    <nameField>
        <displayFormat>FQ-{00000}</displayFormat>
        <label>Freelancer Questionnaire Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Freelancer Questionnaires</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Freelancer_Questionnaire__c/fields/Agree_to_terms__c.field-meta.xml
<CustomField>
    <fullName>Agree_to_terms__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Questionnaire Attestation</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Freelancer_Questionnaire__c/fields/Business_Name__c.field-meta.xml
<CustomField>
    <fullName>Business_Name__c</fullName>
    <label>Business Name</label>
    <length>255</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Freelancer_Questionnaire__c/fields/business_registration_number__c.field-meta.xml
<CustomField>
    <fullName>business_registration_number__c</fullName>
    <label>Business Registration Number</label>
    <length>80</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Freelancer_Questionnaire__c/fields/Client_Count__c.field-meta.xml
<CustomField>
    <fullName>Client_Count__c</fullName>
    <label>Clients Last 12 Months</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>Questionnaire_Type__c</controllingField>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>0 or 1</fullName>
            </value>
            <value>
                <fullName>2-5</fullName>
            </value>
            <value>
                <fullName>6 or more</fullName>
            </value>
            <value>
                <fullName>1</fullName>
            </value>
            <value>
                <fullName>2</fullName>
            </value>
            <value>
                <fullName>3</fullName>
            </value>
            <value>
                <fullName>4 or more</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Freelancer_Questionnaire__c/fields/completed_all_required_registrations__c.field-meta.xml
<CustomField>
    <fullName>completed_all_required_registrations__c</fullName>
    <label>Business Registration Complete</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Yes</fullName>
            </value>
            <value>
                <fullName>No</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Freelancer_Questionnaire__c/fields/Country__c.field-meta.xml
<CustomField>
    <fullName>Country__c</fullName>
    <label>Country</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>Questionnaire_Type__c</controllingField>
        <valueSetDefinition>
            <value>
                <fullName>Afghanistan</fullName>
            </value>
            <value>
                <fullName>Albania</fullName>
            </value>
            <value>
                <fullName>Algeria</fullName>
            </value>
            <value>
                <fullName>Andorra</fullName>
            </value>
            <value>
                <fullName>Angola</fullName>
            </value>
            <value>
                <fullName>Antigua and Barbuda</fullName>
            </value>
            <value>
                <fullName>Argentina</fullName>
            </value>
            <value>
                <fullName>Armenia</fullName>
            </value>
            <value>
                <fullName>Australia</fullName>
            </value>
            <value>
                <fullName>Austria</fullName>
            </value>
            <value>
                <fullName>Azerbaijan</fullName>
            </value>
            <value>
                <fullName>Bahamas</fullName>
            </value>
            <value>
                <fullName>Bahrain</fullName>
            </value>
            <value>
                <fullName>Bangladesh</fullName>
            </value>
            <value>
                <fullName>Barbados</fullName>
            </value>
            <value>
                <fullName>Belarus</fullName>
            </value>
            <value>
                <fullName>Belgium</fullName>
            </value>
            <value>
                <fullName>Belize</fullName>
            </value>
            <value>
                <fullName>Benin</fullName>
            </value>
            <value>
                <fullName>Bhutan</fullName>
            </value>
            <value>
                <fullName>Bolivia</fullName>
            </value>
            <value>
                <fullName>Bosnia and Herzegovina</fullName>
            </value>
            <value>
                <fullName>Botswana</fullName>
            </value>
            <value>
                <fullName>Brazil</fullName>
            </value>
            <value>
                <fullName>Brunei</fullName>
            </value>
            <value>
                <fullName>Bulgaria</fullName>
            </value>
            <value>
                <fullName>Burkina Faso</fullName>
            </value>
            <value>
                <fullName>Burundi</fullName>
            </value>
            <value>
                <fullName>Cabo Verde</fullName>
            </value>
            <value>
                <fullName>Cambodia</fullName>
            </value>
            <value>
                <fullName>India</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Freelancer_Questionnaire__c/fields/Document_Upload__c.field-meta.xml
<CustomField>
    <fullName>Document_Upload__c</fullName>
    <label>Document Upload</label>
    <length>80</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Freelancer_Questionnaire__c/fields/Employeement_Detail__c.field-meta.xml
<CustomField>
    <fullName>Employeement_Detail__c</fullName>
    <label>RD Employment Detail</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Freelancer_Questionnaire__c/fields/Employees_Contractor_Count__c.field-meta.xml
<CustomField>
    <fullName>Employees_Contractor_Count__c</fullName>
    <label>Business Employees/Contractor Count</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>0 to 3</fullName>
            </value>
            <value>
                <fullName>4 or more</fullName>
            </value>
            <value>
                <fullName>0 or 1</fullName>
                <isActive>false</isActive>
                <label>0 or 1</label>
            </value>
            <value>
                <fullName>2-5</fullName>
                <isActive>false</isActive>
                <label>2-5</label>
            </value>
            <value>
                <fullName>6 or more</fullName>
                <isActive>false</isActive>
                <label>6 or more</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Freelancer_Questionnaire__c/fields/Form_Of_Business__c.field-meta.xml
<CustomField>
    <fullName>Form_Of_Business__c</fullName>
    <label>Form Of Business</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Limited Liability Company</fullName>
            </value>
            <value>
                <fullName>Limited Partnership</fullName>
            </value>
            <value>
                <fullName>Corporation</fullName>
            </value>
            <value>
                <fullName>Sole Proprietorship / Individual Entrepreneur</fullName>
            </value>
            <value>
                <fullName>None, I do not have a business.</fullName>
            </value>
            <value>
                <fullName>Other</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Freelancer_Questionnaire__c/fields/Initiate_Approval_Process__c.field-meta.xml
<CustomField>
    <fullName>Initiate_Approval_Process__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Initiate Approval Process</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Freelancer_Questionnaire__c/fields/Insurance_requirement__c.field-meta.xml
<CustomField>
    <fullName>Insurance_requirement__c</fullName>
    <label>Insurance requirement</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>YES - I understand the minimum insurance requirements listed above are required during the agreement / assignment period. I am willing to obtain this insurance if I am engaged on a project.</fullName>
            </value>
            <value>
                <fullName>NO -  I do not agree to the insurance requirements.</fullName>
            </value>
            <value>
                <fullName>Unsure, I need to better understand the cost to determine if I am willing to obtain this insurance. (If you select this response you will need to be prepared to obtain insurance and provide a COI to complete phase 2.)</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Freelancer_Questionnaire__c/fields/Other_Form_of_Business__c.field-meta.xml
<CustomField>
    <fullName>Other_Form_of_Business__c</fullName>
    <label>Form of Business Other</label>
    <length>80</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Freelancer_Questionnaire__c/fields/Other_Investment__c.field-meta.xml
<CustomField>
    <fullName>Other_Investment__c</fullName>
    <label>Investments Other</label>
    <length>80</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Freelancer_Questionnaire__c/fields/Other_Market_Your_Service__c.field-meta.xml
<CustomField>
    <fullName>Other_Market_Your_Service__c</fullName>
    <label>Marketing Services Other</label>
    <length>80</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Freelancer_Questionnaire__c/fields/Signature__c.field-meta.xml
<CustomField>
    <fullName>Signature__c</fullName>
    <label>Signature</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Freelancer_Questionnaire__c/fields/State_of_Business__c.field-meta.xml
<CustomField>
    <fullName>State_of_Business__c</fullName>
    <label>Business Registered State</label>
    <length>80</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Freelancer_Questionnaire__c/fields/State_of_residence__c.field-meta.xml
<CustomField>
    <fullName>State_of_residence__c</fullName>
    <label>State of Residence</label>
    <length>80</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Freelancer_Questionnaire__c/fields/Torc_User__c.field-meta.xml
<CustomField>
    <fullName>Torc_User__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Torc User</label>
    <referenceTo>Torc_User__c</referenceTo>
    <relationshipLabel>Freelancer Questionnaires</relationshipLabel>
    <relationshipName>Freelancer_Questionnaires</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Freelancer_Questionnaire__c/fields/Worked_As_Employee__c.field-meta.xml
<CustomField>
    <fullName>Worked_As_Employee__c</fullName>
    <label>Past RD Employee</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Yes</fullName>
            </value>
            <value>
                <fullName>No</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Torc_Job_Opportunity__c/Torc_Job_Opportunity__c.object-meta.xml
<CustomObject>
    <label>Torc Job Opportunity</label>
    <nameField>
        <label>Torc Job Opportunity Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Torc Job Opportunities</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Torc_Job_Opportunity__c/fields/status__c.field-meta.xml
<CustomField>
    <fullName>status__c</fullName>
    <label>Status</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Torc_Match__c/Torc_Match__c.object-meta.xml
<CustomObject>
    <label>Torc Match</label>
    <nameField>
        <displayFormat>M-{00000}</displayFormat>
        <label>Torc Match Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Torc Matches</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Torc_Match__c/fields/Torc_Job_Opportunity__c.field-meta.xml
<CustomField>
    <fullName>Torc_Job_Opportunity__c</fullName>
    <label>Torc Job Opportunity</label>
    <referenceTo>Torc_Job_Opportunity__c</referenceTo>
    <relationshipLabel>Torc Matches</relationshipLabel>
    <relationshipName>Torc_Matchs</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Torc_Match__c/fields/Torc_User__c.field-meta.xml
<CustomField>
    <fullName>Torc_User__c</fullName>
    <formula>IF(Torc_Application__c&lt;&gt;NULL, Torc_Application__r.Torc_User__r.Name, Torc_User_Ref__r.Name)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Torc User</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Torc_User__c/Torc_User__c.object-meta.xml
<CustomObject>
    <label>Torc User</label>
    <nameField>
        <label>Torc User Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Torc Users</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Torc_User__c/fields/Country__c.field-meta.xml
<CustomField>
    <fullName>Country__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Country</label>
    <referenceTo>Torc_Country__c</referenceTo>
    <relationshipLabel>Torc Users</relationshipLabel>
    <relationshipName>Torc_Users</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Torc_User__c/fields/Full_Name__c.field-meta.xml
<CustomField>
    <fullName>Full_Name__c</fullName>
    <formula>given_name__c +&apos; &apos; + family_Name__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Full Name</label>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/QuestionnaireTest.cls
@isTest (SeeallData=false)
private class QuestionnaireTest 
{
    @testSetup
    public static void T()
    {
        testUtils.setupAllTestData('QUESTION');
    }
    @isTest
    private static void test1() 
    {        
        Test.startTest();
        Torc_User__c tu=[Select id,email__c from Torc_user__c LIMIT 1];
        PageReference pageRef = Page.Questionnaire;
        Test.setCurrentPageReference(pageRef);
        Questionnaire aCls = new Questionnaire();
        aCls.showNONUSBased();
        aCls.rec.Full_Name__c = 'Sumit Mishra';
        aCls.rec.Email__c = 'sumitmishra041979@gmail.com';
        aCls.rec.Business_Name__c = 'Cloud2Crowd';
        aCls.rec.Form_Of_Business__c = 'Other';
        aCls.rec.Client_Count__c = '0 or 1';
        aCls.rec.Worked_As_Employee__c = 'No';
        aCls.rec.Employeement_Detail__c = '';
        aCls.marketServicelst.options[0].chk=true;
        aCls.investmentlst.options[0].chk=true;
        aCls.rec.completed_all_required_registrations__c = 'Yes';
        aCls.rec.business_registration_number__c = 'G000100000010001';
        aCls.rec.Agree_to_terms__c = TRUE;
        aCls.rec.Country__c = 'India';
        aCls.rec.Other_Market_Your_Service__c = '';
        aCls.rec.Document_Upload__c = '';
        aCls.rec.Other_Investment__c = '';
        aCls.rec.Initiate_Approval_Process__c = FALSE;
        aCls.rec.Other_Form_of_Business__c = 'Test';
        aCls.rec.Signature__c = '';
        aCls.rec.State_of_residence__c = '';
        aCls.rec.State_of_Business__c = '';
        aCls.rec.Employees_Contractor_Count__c = '';
        aCls.rec.Insurance_requirement__c = '';
        
        aCls.filename1='abc.pdf';
        aCls.filename2='abc.pdf';
        aCls.uploadedFile1 = Blob.valueOf('This is dummy content');
        aCls.uploadedFile2 = Blob.valueOf('This is dummy content');
        
        aCls.next();
        aCls.Save();
        aCls.previous();
        
    }
    @isTest
    private static void test2() 
    {        
        Test.startTest();
        Torc_User__c tu=[Select id,email__c from Torc_user__c LIMIT 1];
        PageReference pageRef = Page.Questionnaire;
        Test.setCurrentPageReference(pageRef);
        Questionnaire aCls = new Questionnaire();
        aCls.showUSBased();
        aCls.rec.Full_Name__c = 'Sumit Mishra';
        aCls.rec.Email__c = 'sumitmishra041979@gmail.com';
        aCls.rec.Business_Name__c = 'Cloud2Crowd';
        aCls.rec.Form_Of_Business__c = 'Other';
        aCls.rec.Client_Count__c = '0 or 1';
        aCls.rec.Worked_As_Employee__c = 'No';
        aCls.rec.Employeement_Detail__c = '';
        aCls.marketServicelst.options[0].chk=true;
        aCls.investmentlst.options[0].chk=true;
        aCls.rec.completed_all_required_registrations__c = 'Yes';
        aCls.rec.business_registration_number__c = 'G000100000010001';
        aCls.rec.Agree_to_terms__c = TRUE;
        aCls.rec.Other_Market_Your_Service__c = '';
        aCls.rec.Document_Upload__c = '';
        aCls.rec.Other_Investment__c = '';
        aCls.rec.Initiate_Approval_Process__c = FALSE;
        aCls.rec.Other_Form_of_Business__c = 'Test';
        aCls.rec.Signature__c = '';
        aCls.rec.State_of_residence__c = 'Boston';
        aCls.rec.State_of_Business__c = 'new york';
        //aCls.rec.Employees_Contractor_Count__c = '';
        //aCls.rec.Insurance_requirement__c = '';
        aCls.Save();
    }
    @isTest
    private static void test3() 
    {        
        Test.startTest();
        PageReference pageRef = Page.Questionnaire;
        Test.setCurrentPageReference(pageRef);
        System.currentPageReference().getParameters().put('type','US');
        Questionnaire aCls = new Questionnaire();
    }
    @isTest
    private static void test4() 
    {        
        Test.startTest();
        Torc_Match__c tm=[Select ID,Torc_Job_Opportunity__c, Status__c from Torc_Match__c where status__c !='ACCEPTED' and torc_User_ref__c!=NULL LIMIT 1];
        Opportunity opp=[Select id,Job_Opportunity__c from Opportunity Where Torc_Opportunity__c=TRUE and IsWON=TRUE Order By closeDate DESC LIMIT 1];
        opp.Job_Opportunity__c = tm.Torc_Job_Opportunity__c;
        update opp;
        tm.Status__c='ACCEPTED';
        update tm;
    }
    @isTest
    private static void test5() 
    {        
        Freelancer_Questionnaire__c rec=new Freelancer_Questionnaire__c();
        rec.Full_Name__c = 'Sumit Mishra';
        rec.Email__c = 'sumitmishra041979@gmail.com';
        rec.Business_Name__c = 'Cloud2Crowd';
        rec.Form_Of_Business__c = 'Other';
        rec.Client_Count__c = '0 or 1';
        rec.Worked_As_Employee__c = 'No';
        rec.Employeement_Detail__c = '';
        rec.completed_all_required_registrations__c = 'Yes';
        rec.business_registration_number__c = 'G000100000010001';
        rec.Agree_to_terms__c = TRUE;
        rec.Other_Market_Your_Service__c = '';
        rec.Document_Upload__c = '';
        rec.Other_Investment__c = '';
        rec.Initiate_Approval_Process__c = FALSE;
        rec.Other_Form_of_Business__c = 'Test';
        rec.Signature__c = '';
        rec.State_of_residence__c = 'Boston';
        rec.State_of_Business__c = 'new york';
        rec.approval_status__c='Pending';
        ApexPages.StandardController sc = new ApexPages.StandardController(rec);
        PageReference pageRef = Page.approveRejectRequest;
        Test.setCurrentPageReference(pageRef);
        approveRejectRequest apx = new approveRejectRequest(sc);
        apx.launch();
        apx.test1();
        
    }        
}