force-app/main/default/objects/Freelancer_Questionnaire__c/Freelancer_Questionnaire__c.object-meta.xml
<CustomObject>
    <label>Freelancer Questionnaire</label>
    <nameField>
        <displayFormat>FQ-{00000}</displayFormat>
        <label>Freelancer Questionnaire Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Freelancer Questionnaires</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Freelancer_Questionnaire__c/fields/Agree_to_terms__c.field-meta.xml
<CustomField>
    <fullName>Agree_to_terms__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Questionnaire Attestation</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Freelancer_Questionnaire__c/fields/Client_Count__c.field-meta.xml
<CustomField>
    <fullName>Client_Count__c</fullName>
    <label>Clients Last 12 Months</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>Questionnaire_Type__c</controllingField>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>0 or 1</fullName>
            </value>
            <value>
                <fullName>2-5</fullName>
            </value>
            <value>
                <fullName>6 or more</fullName>
            </value>
            <value>
                <fullName>1</fullName>
            </value>
            <value>
                <fullName>2</fullName>
            </value>
            <value>
                <fullName>3</fullName>
            </value>
            <value>
                <fullName>4 or more</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Freelancer_Questionnaire__c/fields/Country__c.field-meta.xml
<CustomField>
    <fullName>Country__c</fullName>
    <label>Country</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>Questionnaire_Type__c</controllingField>
        <valueSetDefinition>
            <value>
                <fullName>Afghanistan</fullName>
            </value>
            <value>
                <fullName>Albania</fullName>
            </value>
            <value>
                <fullName>Algeria</fullName>
            </value>
            <value>
                <fullName>Andorra</fullName>
            </value>
            <value>
                <fullName>Angola</fullName>
            </value>
            <value>
                <fullName>Antigua and Barbuda</fullName>
            </value>
            <value>
                <fullName>Argentina</fullName>
            </value>
            <value>
                <fullName>Armenia</fullName>
            </value>
            <value>
                <fullName>Australia</fullName>
            </value>
            <value>
                <fullName>Austria</fullName>
            </value>
            <value>
                <fullName>Azerbaijan</fullName>
            </value>
            <value>
                <fullName>Bahamas</fullName>
            </value>
            <value>
                <fullName>Bahrain</fullName>
            </value>
            <value>
                <fullName>Bangladesh</fullName>
            </value>
            <value>
                <fullName>Barbados</fullName>
            </value>
            <value>
                <fullName>Belarus</fullName>
            </value>
            <value>
                <fullName>Belgium</fullName>
            </value>
            <value>
                <fullName>Belize</fullName>
            </value>
            <value>
                <fullName>Benin</fullName>
            </value>
            <value>
                <fullName>Bhutan</fullName>
            </value>
            <value>
                <fullName>Bolivia</fullName>
            </value>
            <value>
                <fullName>Bosnia and Herzegovina</fullName>
            </value>
            <value>
                <fullName>Botswana</fullName>
            </value>
            <value>
                <fullName>Brazil</fullName>
            </value>
            <value>
                <fullName>Brunei</fullName>
            </value>
            <value>
                <fullName>Bulgaria</fullName>
            </value>
            <value>
                <fullName>Burkina Faso</fullName>
            </value>
            <value>
                <fullName>Burundi</fullName>
            </value>
            <value>
                <fullName>Cabo Verde</fullName>
            </value>
            <value>
                <fullName>Cambodia</fullName>
            </value>
            <value>
                <fullName>United States</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Freelancer_Questionnaire__c/fields/Employeement_Detail__c.field-meta.xml
<CustomField>
    <fullName>Employeement_Detail__c</fullName>
    <label>RD Employment Detail</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Freelancer_Questionnaire__c/fields/Employees_Contractor_Count__c.field-meta.xml
<CustomField>
    <fullName>Employees_Contractor_Count__c</fullName>
    <label>Business Employees/Contractor Count</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>0 to 3</fullName>
            </value>
            <value>
                <fullName>4 or more</fullName>
            </value>
            <value>
                <fullName>0 or 1</fullName>
                <isActive>false</isActive>
                <label>0 or 1</label>
            </value>
            <value>
                <fullName>2-5</fullName>
                <isActive>false</isActive>
                <label>2-5</label>
            </value>
            <value>
                <fullName>6 or more</fullName>
                <isActive>false</isActive>
                <label>6 or more</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Freelancer_Questionnaire__c/fields/Form_Of_Business__c.field-meta.xml
<CustomField>
    <fullName>Form_Of_Business__c</fullName>
    <label>Form Of Business</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Limited Liability Company</fullName>
            </value>
            <value>
                <fullName>Limited Partnership</fullName>
            </value>
            <value>
                <fullName>Corporation</fullName>
            </value>
            <value>
                <fullName>Sole Proprietorship / Individual Entrepreneur</fullName>
            </value>
            <value>
                <fullName>None, I do not have a business.</fullName>
            </value>
            <value>
                <fullName>Other</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Freelancer_Questionnaire__c/fields/How_You_market__c.field-meta.xml
<CustomField>
    <fullName>How_You_market__c</fullName>
    <label>Marketing Services</label>
    <type>MultiselectPicklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Email</fullName>
            </value>
            <value>
                <fullName>Online Ads, Social Media, Website, PodCast or Blog Posts</fullName>
            </value>
            <value>
                <fullName>Freelancer Platforms such as Torc, Upwork, TopTal, Linkedin or others</fullName>
            </value>
            <value>
                <fullName>Networking events or Tradeshows</fullName>
            </value>
            <value>
                <fullName>Word of Mouth</fullName>
            </value>
            <value>
                <fullName>Website, GitHub, etc</fullName>
            </value>
            <value>
                <fullName>I do not market my services</fullName>
            </value>
            <value>
                <fullName>Other</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Freelancer_Questionnaire__c/fields/Insurance_requirement__c.field-meta.xml
<CustomField>
    <fullName>Insurance_requirement__c</fullName>
    <label>Insurance requirement</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>YES - I understand the minimum insurance requirements listed above are required during the agreement / assignment period. I am willing to obtain this insurance if I am engaged on a project.</fullName>
            </value>
            <value>
                <fullName>NO -  I do not agree to the insurance requirements.</fullName>
            </value>
            <value>
                <fullName>Unsure, I need to better understand the cost to determine if I am willing to obtain this insurance. (If you select this response you will need to be prepared to obtain insurance and provide a COI to complete phase 2.)</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Freelancer_Questionnaire__c/fields/Investements__c.field-meta.xml
<CustomField>
    <fullName>Investements__c</fullName>
    <label>Investments</label>
    <type>MultiselectPicklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Business Insurance</fullName>
            </value>
            <value>
                <fullName>Equipment or Software</fullName>
            </value>
            <value>
                <fullName>Office Space or Co-working Space</fullName>
            </value>
            <value>
                <fullName>Marketing, Accounting or Legal Services</fullName>
            </value>
            <value>
                <fullName>Continuing Education</fullName>
            </value>
            <value>
                <fullName>Website</fullName>
            </value>
            <value>
                <fullName>I have not made any business investments</fullName>
            </value>
            <value>
                <fullName>Other</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Freelancer_Questionnaire__c/fields/Other_Form_of_Business__c.field-meta.xml
<CustomField>
    <fullName>Other_Form_of_Business__c</fullName>
    <label>Form of Business Other</label>
    <length>80</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Freelancer_Questionnaire__c/fields/Other_Investment__c.field-meta.xml
<CustomField>
    <fullName>Other_Investment__c</fullName>
    <label>Investments Other</label>
    <length>80</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Freelancer_Questionnaire__c/fields/Other_Market_Your_Service__c.field-meta.xml
<CustomField>
    <fullName>Other_Market_Your_Service__c</fullName>
    <label>Marketing Services Other</label>
    <length>80</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Freelancer_Questionnaire__c/fields/Questionnaire_Type__c.field-meta.xml
<CustomField>
    <fullName>Questionnaire_Type__c</fullName>
    <label>Questionnaire Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>US</fullName>
            </value>
            <value>
                <fullName>Non-US</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Freelancer_Questionnaire__c/fields/Worked_As_Employee__c.field-meta.xml
<CustomField>
    <fullName>Worked_As_Employee__c</fullName>
    <label>Past RD Employee</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Yes</fullName>
            </value>
            <value>
                <fullName>No</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/Questionnaire.cls
public without sharing class Questionnaire 
{
    public boolean isUSbased{get;set;}
    public string header{get;set;}
    public boolean showSelection{get;set;}
        
    public boolean isSuccess{get;set;}
    public Freelancer_Questionnaire__c rec{get;set;}
    public multipick marketServicelst{get;set;}
    public multipick investmentlst{get;set;}
    public multipick formOfBusinesslst{get;set;}
    public multipick clientCountlst{get;set;}
    
    public multipick employeeCountlst{get;set;}
    public multipick insuranceNeedlst{get;set;}
    
    
    public string fngett{get;set;}
    public string valgett{get;set;}
    public void setFormOfBusiness()
    {
        rec.put(fngett,valgett); 
    }
    public Questionnaire()
    {
        showSelection = false;
        if(ApexPages.currentPage().getParameters().get('type')!='US' && ApexPages.currentPage().getParameters().get('type')!='NONUS')
        {
            showSelection = true;
            return;
        }
        isUSbased = ApexPages.currentPage().getParameters().get('type')=='US'; 
        initialProcess();       
    }
    public void showUSBased()
    {
        showSelection = false;
        isUSbased = true;
        initialProcess();
    }
    public void showNonUSBased()
    {
        showSelection = false;
        isUSbased = false;
        initialProcess();
    }
    public void initialProcess()
    {
        errorFile1=errorFile2='';
        header = isUSbased?'Freelancer Questionnaire - US based Freelancers':'Freelancer Questionnaire - non-US based Freelancers';
        rec = new Freelancer_Questionnaire__c(Questionnaire_Type__c = (isUSbased?'US':'Non-US'));
        if(isUSbased)
            rec.Country__c='United States';
        
        marketServicelst = new multipick(Freelancer_Questionnaire__c.How_You_market__c.getDescribe(),'Other_Market_Your_Service__c',rec,true,'How_You_market__c',isUSbased);
        investmentlst = new multipick(Freelancer_Questionnaire__c.Investements__c.getDescribe(),'Other_Investment__c',rec,true,'Investements__c',isUSbased);
        formOfBusinesslst = new multipick(Freelancer_Questionnaire__c.Form_Of_Business__c.getDescribe(),'Other_Form_of_Business__c',rec,true,'Form_Of_Business__c',isUSbased);
        clientCountlst = new multipick(Freelancer_Questionnaire__c.Client_Count__c.getDescribe(),'',rec,true,'Client_Count__c',isUSbased);
        employeeCountlst = new multipick(Freelancer_Questionnaire__c.Employees_Contractor_Count__c.getDescribe(),'',rec,true,'Employees_Contractor_Count__c',isUSbased);
        insuranceNeedlst = new multipick(Freelancer_Questionnaire__c.Insurance_requirement__c.getDescribe(),'',rec,true,'Insurance_requirement__c',isUSbased);
        isSuccess = false;
        screen=1;
    }
    public integer screen{get;set;}
    public void next()
    {
        errorFile1=errorFile2='';
        boolean err=false;
        if(rec.Worked_As_employee__c=='Yes' && (rec.Employeement_Detail__c==NULL || rec.Employeement_Detail__c.length()<1))
        {
            rec.Employeement_Detail__c.addError('Please fill');
            err=true;
        }
        if(!marketServicelst.isRequiredok())
            err=true;
        if(!investmentlst.isRequiredok())
            err=true;
        if(!formOfBusinesslst.isRequiredokOpt())
            err=true;
        if(!clientCountlst.isRequiredokOpt())
            err=true;
        
        if(isUSBased)
        {
            if(!employeeCountlst.isRequiredokOpt())
                err=true;
            if(!insuranceNeedlst.isRequiredokOpt())
                err=true;
        }  
        if(!err)
            screen=2;      
    }
    public void previous()
    {
        errorFile1=errorFile2='';
        screen=1;
    }
    public void Save()
    {
        boolean err=false;
        boolean haveUp1=true;
        boolean haveUp2=true;
        if(rec.Agree_to_terms__c==false)
        {
            rec.Agree_to_terms__c.addError('Please check');
            err=true;
        }
        if(uploadedFile1==null)
        {
            errorFile1 = 'Please Upload document.';
            err=true;
            haveUp1=false;
        }
        if(uploadedFile2==null)
        {
            errorFile2 = 'Please Upload document.';
            err=true;
            haveUp2=false;
        }
       
        if(!err)
        {
            insert rec;
            uploadfile();
            isSuccess=true;
        }
        else
        {
            errorFile1 = haveUp1?'Please re-upload document.': 'Please Upload document.';
            errorFile2 = haveUp2?'Please re-upload document.': 'Please Upload document.';
        }    
    }
    
    public class multipick
    {
        public boolean isUSbased{get;set;}
        public string fieldName{get;set;}
        public boolean isCheckbox{get;set;}
        public string errorType{get;set;}
        public string otherValue{get;set;}
        public List<pickoption> options{get;set;}
        public Freelancer_Questionnaire__c record{get;set;}
        public string otherField{get;set;}
        public multipick(Schema.DescribeFieldResult fieldResult,string ofield,Freelancer_Questionnaire__c r,boolean icb,string feildnm,boolean isUS)
        {
            isUSBased = isUS;
            fieldname=feildnm;
            isCheckbox = icb;
            errorType = '';
            record =r;
            otherField = ofield;
            otherValue='';
            options = new List<pickoption>();
            if(fieldName=='Client_Count__c')
            {
                if(isUSbased)
                {
                    options.add(new pickOption('1',record,fieldname));
                    options.add(new pickOption('2',record,fieldname));
                    options.add(new pickOption('3',record,fieldname));
                    options.add(new pickOption('4 or more',record,fieldname));
                }
                else
                {
                    options.add(new pickOption('0 or 1 ',record,fieldname));
                    options.add(new pickOption('2-5',record,fieldname));
                    options.add(new pickOption('6 or more',record,fieldname));
                }
            }
            else
            {
                for (Schema.PicklistEntry entry : fieldResult.getPicklistValues()) 
                {
                    options.add(new pickOption(entry.getLabel(),record,fieldname));
                }
            }    
        }
        public boolean isRequiredok()
        {
            errorType ='';
            boolean atleast1=false;
            string res='';
            for(pickoption po:options)
            {
                if(po.chk)
                {
                    atleast1=true;
                    res = res+(res==''?po.label:('; '+po.Label));
                }    
                if(po.chk && po.label=='Other' && otherField!='' && (record.get(otherField)==NULL || record.get(otherField)==''))
                {
                    errorType= 'Add value in other';
                    return false;
                }    
            }
            record.put(fieldName,res);
            errorType = atleast1?'':'Select an option';
            return atleast1;
        }
        public boolean isRequiredokOpt()
        {
            errorType ='';
            if(record.get(fieldName)=='' || record.get(fieldName)==null)
            {
                errorType =  'Select an option';
                return false;
            }    
            if(record.get(fieldName)=='Other' && otherField!='' && (record.get(otherField)==NULL || record.get(otherField)==''))
            {
                errorType= 'Add value in other';
                return false;
            }
            
            return true;
        }
    }
    public transient Blob uploadedFile1 { get; set; }
    public String fileName1 { get; set; }
    public transient Blob uploadedFile2 { get; set; }
    public String fileName2 { get; set; }
    public string errorFile1{ get; set; }
    public string errorFile2{ get; set; }
    public void uploadFile()
    {
        uploadFile(uploadedFile1, fileName1);
        uploadFile(uploadedFile2, fileName2);
    }
    public void uploadFile(Blob uploadedFile, String fileName)
    {
        if (uploadedFile != null && fileName != null) 
        {
            String contentType;
            String extension = fileName.substringAfterLast('.').toLowerCase();
            switch on extension {
                when 'pdf'       { contentType = 'application/pdf'; }
                when 'png'       { contentType = 'image/png'; }
                when 'jpg', 'jpeg' { contentType = 'image/jpeg'; }
                when 'gif'       { contentType = 'image/gif'; }
                when 'doc'       { contentType = 'application/msword'; }
                when 'docx'      { contentType = 'application/vnd.openxmlformats-officedocument.wordprocessingml.document'; }
                when 'xls'       { contentType = 'application/vnd.ms-excel'; }
                when 'xlsx'      { contentType = 'application/vnd.openxmlformats-officedocument.spreadsheetml.sheet'; }
                when 'txt'       { contentType = 'text/plain'; }
                when else        { contentType = 'application/octet-stream'; } // generic fallback
            }
        
        
        
            Attachment att = new Attachment();
            att.ParentId = rec.Id;
            att.Name = fileName;
            att.Body = uploadedFile;
            att.ContentType = contentType;
            insert att;
        }               
    }
    public class pickoption
    {
        public string namefld{get;set;}
        public boolean chk{get;set;}
        public string label{get;set;}
        public Freelancer_Questionnaire__c record{get;set;}
        public string getOptiontag()
        {
            string str='<input type="radio" name="'+namefld+'" onclick="setFormOfBusiness(\''+label +'\',\''+namefld +'\')"';
            str=str+(label == record.get(namefld)?' checked ':'');
            return str;
        }
        public pickoption(string lab,Freelancer_Questionnaire__c rec,string nmf)
        {
            record=rec;
            label=lab;
            chk=false;
            namefld = nmf;
        }
    }
}