force-app/main/default/objects/Docusign_Defaults__c/Docusign_Defaults__c.object-meta.xml
<CustomObject>
    <label>Docusign Default</label>
    <nameField>
        <displayFormat>DD-{00}</displayFormat>
        <label>Docusign Defaults No</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Docusign Defaults</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Docusign_Defaults__c/fields/DocuSign_Envelope_Template_MSA__c.field-meta.xml
<CustomField>
    <fullName>DocuSign_Envelope_Template_MSA__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>DocuSign Envelope Template(MSA)</label>
    <referenceTo>dfsle__EnvelopeConfiguration__c</referenceTo>
    <relationshipLabel>Docusign Defaults</relationshipLabel>
    <relationshipName>Docusign_Defaults</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/classes/AccountDocusignredirect.cls
public class AccountDocusignredirect
{
    public Account act{get;set;}
    public AccountDocusignredirect(ApexPages.StandardController controller)
    {
        act=(Account) controller.getRecord();
        act = [Select ID, Name, MSA_Signer__c from Account where ID=:act.id];
    }
    public Pagereference saveAndreturn()
    {
        update act;
        return new pagereference('/'+act.id);   
    }
    public Pagereference reDirect()
    {
        if(act.MSA_Signer__c==NULL)
        {
           act.MSA_Signer__c.addError('Please Select');
           return NULL; 
        }
        update act;
        Docusign_Defaults__c dd =[Select DocuSign_Envelope_Template_MSA__c,DocuSign_Envelope_Template_MSA__r.Name FROM Docusign_Defaults__c LIMIT 1];
        string redirectUrl=site.getPathPrefix() =='/s'?'/apex/dfsle__sending':site.getPathPrefix()+'/apex/dfsle__sending';
        redirectUrl = redirectUrl +'?sId='+act.Id
              + '&templateId=' + dd.DocuSign_Envelope_Template_MSA__c
              + '&recordId='+act.Id
              + '&title='+ EncodingUtil.urlEncode(dd.DocuSign_Envelope_Template_MSA__r.Name,'UTF-8');    
        return new pagereference(redirectUrl)  ;      
    }
}