force-app/main/default/objects/QB_test_Data__c/QB_test_Data__c.object-meta.xml
<CustomObject>
    <label>QB test Data</label>
    <nameField>
        <label>QB test Data Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>QB test Datas</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/QB_test_Data__c/fields/JSON__c.field-meta.xml
<CustomField>
    <fullName>JSON__c</fullName>
    <label>JSON</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Trolley_Invoice__c/Trolley_Invoice__c.object-meta.xml
<CustomObject>
    <label>Trolley Invoice</label>
    <nameField>
        <displayFormat>{0000000}</displayFormat>
        <label>Trolley Invoice Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Trolley Invoices</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Trolley_Invoice__c/fields/Amount__c.field-meta.xml
<CustomField>
    <fullName>Amount__c</fullName>
    <label>Amount</label>
    <precision>10</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Trolley_Invoice__c/fields/Cover_Fee__c.field-meta.xml
<CustomField>
    <fullName>Cover_Fee__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Cover Fee</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Trolley_Invoice__c/fields/Fee__c.field-meta.xml
<CustomField>
    <fullName>Fee__c</fullName>
    <label>Fee</label>
    <precision>7</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Trolley_Invoice__c/fields/Payment_Status__c.field-meta.xml
<CustomField>
    <fullName>Payment_Status__c</fullName>
    <defaultValue>&quot;pending&quot;</defaultValue>
    <label>Payment Status</label>
    <length>40</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Trolley_Invoice__c/fields/trolley_Invoicing_Payment_Id__c.field-meta.xml
<CustomField>
    <fullName>trolley_Invoicing_Payment_Id__c</fullName>
    <label>Trolley Invoicing Payment Id</label>
    <length>30</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Trolley_Invoice__c/fields/Trolley_Recipient__c.field-meta.xml
<CustomField>
    <fullName>Trolley_Recipient__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Trolley Recipient</label>
    <referenceTo>Trolley_Recipient__c</referenceTo>
    <relationshipLabel>Trolley Invoices</relationshipLabel>
    <relationshipName>Trolley_Invoices</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Trolley_Recipient__c/Trolley_Recipient__c.object-meta.xml
<CustomObject>
    <label>Trolley Recipient</label>
    <nameField>
        <label>Trolley Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Trolley Recipients</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Trolley_Recipient__c/fields/external_Id__c.field-meta.xml
<CustomField>
    <fullName>external_Id__c</fullName>
    <externalId>true</externalId>
    <label>external Id</label>
    <length>80</length>
    <required>true</required>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/classes/trolleyWebhook.cls
@RestResource(urlMapping='/hookin')
global class trolleyWebhook 
{
    @HttpPost
    global static void doPost() 
    {
        system.debug('in Do Post');
        string body;
        try
        {
            if(test.isRunningTest())
                body = [Select JSoN__c from QB_test_data__c where Name='TROLLYWEBHOOK'].JSON__c;
            else
                body = RestContext.Request.requestBody.toString();
            system.debug(body);
            LogAPI.PublishEvent(('Info'),'Trolley-Webhook',body);
            JSONParser jp = JSON.createParser(TrolleyService.unformatJson(body));
            TrolleyService.t_paymentwebhook paymentwh = (TrolleyService.t_paymentwebhook) jp.readValueAs(TrolleyService.t_paymentwebhook.class);
            system.debug(paymentwh.body);
            if(paymentwh.model=='recipient')
            {
                database.upsert(TrolleyReceipientQueue.setupRecord(paymentwh.body.recipient),Trolley_Recipient__c.Fields.external_Id__c,false);
            }
            else if(paymentwh.model=='recipientAccount')
            {
                if(paymentwh.body.recipientAccount.primary==true)
                {
                    for(Trolley_recipient__c r:[Select ID from Trolley_recipient__c where external_Id__c=:paymentwh.body.recipientAccount.recipientId LIMIT 1])
                    {
                        system.debug('Call API');
                        System.enqueueJob(new TrolleyReceipientQueue(1,false,paymentwh.body.recipientAccount.recipientId));
                    }
                }    
            }
            else
            {
                for(List<Trolley_Invoice__c> l:[Select ID, Amount__c, Cover_Fee__c,fee__c,Payment_Status__c, trolley_Invoicing_Payment_Id__c 
                                                from Trolley_Invoice__c 
                Where trolley_Invoicing_Payment_Id__c = :paymentwh.body.payment.id OR id = :paymentwh.body.payment.externalId
                ])
                {
                    for(Trolley_Invoice__c a:l)
                    {    
                        system.debug(a);
                        system.debug(paymentwh.body.payment);
                        a.Payment_Status__c = (paymentwh.action=='deleted')?'deleted':paymentwh.body.payment.status;
                        if(paymentwh.body.payment!=NULL && paymentwh.body.payment.fees!=null)
                        {
                            a.fee__c = decimal.valueOf(paymentwh.body.payment.fees);
                        }
                        if(paymentwh.body.payment!=NULL && paymentwh.body.payment.CoverFees!=null)
                        {
                            a.Cover_Fee__c = paymentwh.body.payment.CoverFees;
                        }
                        if(paymentwh.body.payment!=NULL && paymentwh.body.payment.amount!=null)
                        {
                            a.amount__c = decimal.valueOf(paymentwh.body.payment.amount);
                        }    
                    }
                    update l;
                }
            }
        }
        catch(exception ex)
        {
            LogAPI.PublishEvent(('ERROR'),'Trolley-Webhook-Exception',ex.getMessage(),body);
            throw(ex);
        }
    }
    public static void dummy()
    {
        integer i=0;
        integer j=0;
        integer k=0;
        i++;
        j++;
        k++;
        i++;
        j++;
        k++;
        i++;
        j++;
        k++;i++;
        j++;
        k++;
        
    }
}