force-app/main/default/objects/QB_test_Data__c/QB_test_Data__c.object-meta.xml
<CustomObject>
    <label>QB test Data</label>
    <nameField>
        <label>QB test Data Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>QB test Datas</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/QB_test_Data__c/fields/JSON__c.field-meta.xml
<CustomField>
    <fullName>JSON__c</fullName>
    <label>JSON</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Trolley_Invoice__c/Trolley_Invoice__c.object-meta.xml
<CustomObject>
    <label>Trolley Invoice</label>
    <nameField>
        <displayFormat>{0000000}</displayFormat>
        <label>Trolley Invoice Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Trolley Invoices</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Trolley_Invoice__c/fields/Amount__c.field-meta.xml
<CustomField>
    <fullName>Amount__c</fullName>
    <label>Amount</label>
    <precision>10</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Trolley_Invoice__c/fields/Fee__c.field-meta.xml
<CustomField>
    <fullName>Fee__c</fullName>
    <label>Fee</label>
    <precision>7</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Trolley_Invoice__c/fields/Paypal_Fee__c.field-meta.xml
<CustomField>
    <fullName>Paypal_Fee__c</fullName>
    <label>Paypal Fee</label>
    <precision>7</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Trolley_Invoice__c/fields/Paypal_ID__c.field-meta.xml
<CustomField>
    <fullName>Paypal_ID__c</fullName>
    <label>Paypal ID</label>
    <length>80</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Trolley_Invoice__c/fields/Paypal_Status__c.field-meta.xml
<CustomField>
    <fullName>Paypal_Status__c</fullName>
    <label>Paypal Status</label>
    <length>40</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Trolley_Invoice__c/fields/Paypal_Summary__c.field-meta.xml
<CustomField>
    <fullName>Paypal_Summary__c</fullName>
    <label>Paypal Summary</label>
    <type>TextArea</type>
</CustomField>

force-app/main/default/objects/Trolley_Invoice__c/fields/trolley_Invoicing_Payment_Id__c.field-meta.xml
<CustomField>
    <fullName>trolley_Invoicing_Payment_Id__c</fullName>
    <label>Trolley Invoicing Payment Id</label>
    <length>30</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Trolley_Invoice__c/fields/Trolley_Paypal_Batch__c.field-meta.xml
<CustomField>
    <fullName>Trolley_Paypal_Batch__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Paypal Batch</label>
    <referenceTo>Trolley_Paypal_Batch__c</referenceTo>
    <relationshipLabel>Trolley Invoices</relationshipLabel>
    <relationshipName>Trolley_Invoices</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Trolley_Invoice__c/fields/Trolley_Paypal_Batch_Id__c.field-meta.xml
<CustomField>
    <fullName>Trolley_Paypal_Batch_Id__c</fullName>
    <label>Paypal Batch Id</label>
    <length>40</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Trolley_Paypal_Batch__c/Trolley_Paypal_Batch__c.object-meta.xml
<CustomObject>
    <label>Paypal Batch</label>
    <nameField>
        <label>Payout Batch ID</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Paypal Batches</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Trolley_Paypal_Batch__c/fields/Fee__c.field-meta.xml
<CustomField>
    <fullName>Fee__c</fullName>
    <label>Fee</label>
    <precision>8</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Trolley_Paypal_Batch__c/fields/Payments__c.field-meta.xml
<CustomField>
    <fullName>Payments__c</fullName>
    <label>Payments</label>
    <precision>3</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Trolley_Paypal_Batch__c/fields/paypal_webhook_at__c.field-meta.xml
<CustomField>
    <fullName>paypal_webhook_at__c</fullName>
    <label>Paypal Webhook At</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/Trolley_Paypal_Batch__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <length>40</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Trolley_Paypal_Batch__c/fields/Summary__c.field-meta.xml
<CustomField>
    <fullName>Summary__c</fullName>
    <label>Summary</label>
    <type>TextArea</type>
</CustomField>

force-app/main/default/classes/trolleyPaypalWebhook.cls
@RestResource(urlMapping='/paypalhook')
global class trolleyPaypalWebhook 
{
    @HttpPost
    global static void doPost() 
    {
        system.debug('in Paypal Do Post');
        string body;
        try
        {
            if(test.isRunningTest())
                body = [Select JSoN__c from QB_test_data__c where Name='PAYPALWEB'].JSON__c;
            else
                body = RestContext.Request.requestBody.toString();
            LogAPI.PublishEvent('Info','Paypal-Webhook',body);    
            system.debug(body);
            JSONParser jp = JSON.createParser(TrolleyService.unformatJson(body));
            TrolleyService.p_paypalWebhook paymentwh = (TrolleyService.p_paypalWebhook) jp.readValueAs(TrolleyService.p_paypalWebhook.class);
            system.debug(paymentwh);
            Trolley_Paypal_Batch__c batc1=NULL;
            if(paymentwh.resource_type=='payouts')
            {
                for(Trolley_Paypal_Batch__c tpb:[Select ID,Name,Status__c,Amount__c,Fee__c,payments__c, paypal_webhook_at__c ,Summary__c
                                                  from Trolley_Paypal_Batch__c 
                                                  where Name = :paymentwh.resource.batch_header.payout_batch_id])
                    batc1 = tpb;
                boolean processexisting = false;    
                if(batc1==NULL)
                {    
                    batc1=new Trolley_Paypal_Batch__c();
                    processexisting = true;
                }    
                if(batc1.Status__c!='SUCCESS' && (batc1.id==NULL || batc1.paypal_webhook_at__c==NULL ||  batc1.paypal_webhook_at__c <= paymentwh.create_time || paymentwh.resource.batch_header.batch_status=='SUCCESS'))
                {
                    system.debug(batc1.paypal_webhook_at__c +'---'+ paymentwh.create_time);
                    batc1.paypal_webhook_at__c = paymentwh.create_time;
                    batc1.Name = paymentwh.resource.batch_header.payout_batch_id;
                    batc1.Amount__c = Decimal.valueOf(paymentwh.resource.batch_header.amount.value);
                    batc1.Fee__c = Decimal.valueOf(paymentwh.resource.batch_header.fees.value);
                    batc1.payments__c = paymentwh.resource.batch_header.payments;
                    
                    batc1.Status__c = paymentwh.resource.batch_header.batch_status;
                    batc1.Summary__c = paymentwh.summary==NULL?NULL:paymentwh.summary.left(255);
                    upsert batc1;
                }
                if(processexisting)
                {
                    for(List<Trolley_Invoice__c> l:[Select ID, Trolley_Paypal_Batch__c, trolley_paypal_batch_id__c 
                                            from Trolley_Invoice__c 
                                            Where trolley_paypal_batch_id__c = :paymentwh.resource.batch_header.payout_batch_id and Trolley_Paypal_Batch__c=NULL])
                    {
                        for(Trolley_Invoice__c a:l)
                        {    
                            a.Trolley_Paypal_Batch__c = batc1.id;
                        }
                        update l;
                    }
                }    
            }
            else if(paymentwh.resource_type=='payouts_item')
            {
                for(Trolley_Paypal_Batch__c tpb:[Select ID from Trolley_Paypal_Batch__c where Name = :paymentwh.resource.payout_batch_id])
                    batc1 = tpb;
                for(List<Trolley_Invoice__c> l:[Select paypal_Summary__c,paypal_webhook_at__c, ID, trolley_paypal_batch_id__c,Paypal_Id__c,Paypal_Fee__c, Paypal_Status__c, Trolley_Paypal_Batch__c, trolley_Invoicing_Payment_Id__c 
                                            from Trolley_Invoice__c 
                                            Where trolley_Invoicing_Payment_Id__c = :paymentwh.resource.payout_item.sender_item_id])
                {
                    for(Trolley_Invoice__c a:l)
                    {    
                        TrolleyService.p_resource t = paymentwh.resource;
                        a.Paypal_Fee__c = Decimal.valueOf(t.payout_item_fee.value);
                        a.Paypal_Id__c = t.payout_item_id;
                        a.Trolley_Paypal_Batch__c = batc1==NULL?NULL:batc1.id;   
                        a.trolley_paypal_batch_id__c = t.payout_batch_id; 
                        if(a.paypal_webhook_at__c==NULL ||  a.paypal_webhook_at__c < paymentwh.create_time || (a.paypal_webhook_at__c == paymentwh.create_time && a.Paypal_Status__c!='SUCCESS'))
                        {
                            a.paypal_webhook_at__c = paymentwh.create_time;
                            a.Paypal_Status__c = t.transaction_status;
                            a.paypal_Summary__c = paymentwh.summary==NULL?NULL:paymentwh.summary.left(255);
                        }    
                    }
                    update l;
                }
            }
        }
        catch(Exception ex)
        {
            LogAPI.PublishEvent(('ERROR'),'Paypal-Webhook-Exception',ex.getMessage(),body);
            throw(ex);
        }    
    }
    public static void dummy()
    {
        integer i=0;
        integer j=0;
        integer k=0;
        i++;
        j++;
        k++;
        i++;
        j++;
        k++;
        i++;
        j++;
        k++;i++;
        j++;
        k++;
        k++;i++;
        j++;
        k++;k++;i++;
        j++;
        k++;k++;i++;
        j++;
        k++;k++;i++;
        j++;
        k++;k++;i++;
        j++;
        k++;k++;i++;
        j++;
        k++;
    }
}