force-app/main/default/objects/QB_test_Data__c/QB_test_Data__c.object-meta.xml
<CustomObject>
    <label>QB test Data</label>
    <nameField>
        <label>QB test Data Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>QB test Datas</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/QB_test_Data__c/fields/JSON__c.field-meta.xml
<CustomField>
    <fullName>JSON__c</fullName>
    <label>JSON</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/classes/QB_HttpMock.cls
public class QB_HttpMock implements HttpCalloutMock 
{
   public static string Operation;  
   String returnResult = '';
   
   public QB_HttpMock() 
   {
      this.returnResult = '{"foo":"bar"}';
      if(QBOpportunitySetup.QBAPITestOperation!=NULL)
          for(QB_Test_Data__c QBT:[Select JSON__c from QB_Test_Data__c Where Name=:QBOpportunitySetup.QBAPITestOperation])
              this.returnResult = QBT.Json__c;
   }
   
   public QB_HttpMock(String json) 
   {
      this.returnResult = json;
   }
   
   
   public HTTPResponse respond(HTTPRequest req) 
   {
      HttpResponse response = new HttpResponse();
      response.setStatusCode(200);
      response.setBody(returnResult);
      return response;
  }
}